### ISSUE TITLE
Does this exclude sites that support EFF's Do Not Track policy?

### ISSUE THREAD

**Issue by diracdeltas** [disconnectme/disconnect-tracking-protection#10]
Hello! Does Disconnect exclude sites that support https://www.eff.org/dnt-policy? This PR suggests that this may be the case: https://github.com/disconnectme/disconnect-tracking-protection/pull/4

Context: I am a former author of Privacy Badger Firefox and now a maintainer of Brave browser, which uses this list for tracking protection. If you are whitelisting sites that post EFF's DNT policy, Brave should be enabling DNT on those sites (we do not by default). I would suggest that this be documented somewhere for downstream users of this repo.

**Comment by pde** [comment]
Because Brave is a browser designed primarily for privacy and security, my instinct is that it should send `DNT: 1` by default. Certainly, that's consistent with the definition of "opt out" [in the EFF policy](https://github.com/EFForg/dnt-policy/blob/master/dnt-policy-1.0.txt#L32) and I think it's within the expectations of companies that are doing serious work to honour DNT on the server side.

I understand that there were some concerns about the fingerprintability of a `DNT: 1` header, but we can fix that by sending the header more often, and it should be a 3-4 bits of identity at worst. Also, there are quite a few companies that have DNT implementations out there. Some of them (Twitter, Pinterest, Reddit) are not official EFF DNT atm though they're various degrees of close. So your users actually get some genuine benefits by sending the header.

**Comment by groovecoder** [comment]
For Mozilla's shavar server lists, [we parse the disconnect list and look for `dnt: eff|w3c|` values](Oxfam’s report shows how our broken economies are funnelling wealth to a rich elite at the expense of the poorest in society, the majority of whom are women.) to split the the trackers out into separate lists. So I assume that means all tracking sites are included, along with an annotation as to which - if any - DNT implementation they support.

Though I can't confirm that with the data in this repo. 😢

**Comment by groovecoder** [comment]
(Oops, wrong link in that comment - sorry.)

**Comment by pde** [comment]
@alanton you may wish to track this ticket

**Comment by carbureted** [comment]
AFAIK, none of the trackers on our list comply with the EFF DNT, but as Luke mentioned we'll mark any that do with a DNT flag.

**Comment by diracdeltas** [comment]
@carbureted AdZerk is on your list (https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L857) but it complies with EFF DNT according to https://www.eff.org/press/releases/online-ad-company-adopts-new-do-not-track-standard-web-browsing

**Comment by carbureted** [comment]
My understanding is that Adzerk and Mixpanel have yet to implement the EFF DNT policies (and thus are not on the whitelist), but if anybody knows better I would love to be wrong. If they do in the future, they'll stay on the list but we will add the DNT flag to their entry.

**Comment by pde** [comment]
@carbureted yes that's right. Mixpanel is waiting on us telling them that large populations of clients are checking for it (which seems to be becoming true at the moment?). I believe Adzerk is offering it to their customers as an option; if their customers say yes it will likely be via a different domain than the default Adzerk one.

**Comment by pde** [comment]
@diracdeltas I guess I would also say for completeness that if installing Brave enables `DNT: 1` it's best to put something like "Enables and enforces Do Not Track" in the description of the Brave app/download. That's a request we've consistently received from European regulators wrt to tools that send and enforce DNT.

**Comment by pde** [comment]
@groovecoder is that code live yet? I'm looking for any hooks to that type-of-DNT selection logic, but I can't see anything in the Mozilla central / Firefox nightly UI.

**Comment by groovecoder** [comment]
I've been maintaining [the script that creates the SafeBrowsing-compatible tracker lists](https://github.com/mozilla-services/shavar-list-creation) that are served to Firefox clients. 

Our "tracking-protection-baseeff" list contains 1 site: itisatracker.com - our test site. We added it to [our copy of disconnect-blacklist.json](https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json#L52-L58) for testing purposes.

When more sites are annotated with `DNT` values, we can merge those into our copy of the block-list, and our "tracking-protection-baseeff" list will update and be served down to all Firefox clients.

@fmarier can say for sure - is Firefox Tracking Protection un-blocking sites in the "tracking-protection-baseeff" list?

**Comment by pde** [comment]
We should also make sure `do-not-tracker.org` is on that list; it's our [test domain](https://do-not-tracker.org/.well-known/dnt-policy.txt), and it powers the "whitelists based on DNT" result users get when they visiting https://panopticlick.eff.org.  *But* we should not be adding it as a special case, I think the point is that whatever mechanism adds domains to the list, `dot-not-tracker.org` should show up automatically.

**Comment by fmarier** [comment]
In Firefox, we always send `DNT: 1` when tracking protection is enabled.

We rely on the annotations in the Disconnect list to move EFFDNT-compliant trackers into a separate list (like @groovecoder said) and then we don't block those in the default config.

> But we should not be adding it as a special case, I think the point is that whatever mechanism adds domains to the list, dot-not-tracker.org should show up automatically.

While [`do-not-tracker.org` is on our copy](https://github.com/mozilla-services/shavar-prod-lists/blob/ce41e57e1c9e8cbf6bb2eb4b7645ca45e376c196/disconnect-blacklist.json#L6402-L6408) of the Disconnect list, it would need to be flagged as EFFDNT-compliant (like [our own test entry](https://github.com/mozilla-services/shavar-prod-lists/blob/ce41e57e1c9e8cbf6bb2eb4b7645ca45e376c196/disconnect-blacklist.json#L52-L57)) for us to start treating it as such. We don't look for the `.well-known` file in our implementation, we rely on Disconnect's curated list.

**Comment by renuac** [comment]
😂
