### ISSUE TITLE
Consider adding smartlock.google.com or the google.com base domain to the blocklist

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#101]
See `medium.com` as an example of a site that embeds this. This page makes a request to `https://smartlock.google.com/iframe/request?client=...` which includes the cookies: `ANID` and `NID`, among others. These cookies are scoped to `.google.com` and are advertising-related according to https://policies.google.com/technologies/types?hl=en-US.

Give that these cookies are scoped to `.google.com`, it seems like it's worth considering whether it makes sense to add the base `google.com` domain in place of the current `www.google.com`. Otherwise the list will need to continually be updated to include all `*.google.com` subdomains. since all of these will carry cookies scoped to `.google.com`.

**Comment by englehardt** [comment]
If `google.com` is added to the list, I suspect it would be in place of `www.google.com`, which is in the `Content` category.

If that's the case, I think it would also make sense to include `smartlock.google.com` in the `Social` category. This is the category under which some [competitor products](https://bugzilla.mozilla.org/show_bug.cgi?id=1581050#c0) are classified.

**Comment by patjack** [comment]
@englehardt thanks for flagging this and #100!
