### ISSUE TITLE
Consider adding workplace.com and oculus.com as a Facebook properties in entities.json

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#104]
`workplace.com` appears to be a Facebook property that isn't currently included on the entity list. This has lead to breakage for Firefox users as described in [Bug 1590944](https://bugzilla.mozilla.org/show_bug.cgi?id=1590944) and https://webcompat.com/issues/41132.

**Comment by Daniel15** [comment]
oculus.com is missing too (so it's also currently broken with the default settings in Fenix)

**Comment by englehardt** [comment]
Thanks @Daniel15. I filed [Bug 1591480](https://bugzilla.mozilla.org/show_bug.cgi?id=1591480) to track that.

**Comment by patjack** [comment]
Thanks @englehardt and @Daniel15 for flagging these. I'll push an update shortly.
