### ISSUE TITLE
Consider adding keywee.co as a tracker

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#107]
Example site: `https://www.lemonde.fr/`

Example request: `https://pixel.keywee.co/i?stm=1572385964089&e=pp&url=https%3A%2F%2Fwww.lemonde.fr%2F&page=Le%20Monde.fr%20-%20Actualit%C3%A9s%20et%20Infos%20en%20France%20et%20dans%20le%20monde&pp_mix=0&pp_max=0&pp_miy=0&pp_may=5358&tv=js-2.9.1&tna=cf&aid=484&p=web&tz=America%2FLos_Angeles&lang=en-US&cs=UTF-8&res=X&cd=24&cookie=1&f_passive=1&f_wheel=wheel&eid=&dtm=X&vp=X&ds=1789x15169&vid=1&sid=X&duid=X&fp=X`

This request has a cookie associated with it that appears to be a UUID. See also https://keywee.co/for-publishers/

**Comment by patjack** [comment]
@englehardt thanks for flagging this. We confirmed and we'll be adding this shortly.
