### ISSUE TITLE
blocking the hp.com domain blocks prevents embedded cartridge finder from running

### ISSUE THREAD

**Issue by blathersbugs** [disconnectme/disconnect-tracking-protection#108]
I am a dev at HP and am trying to create a cartridge finder that retail partners can embed on their sites that allows the customer to easily find the correct cartridge for their printer.  currently the broad inclusion of the hp.com domain (which is probably better classified as content, although I won't push that issue now) the script is blocked from using cookies or the storage api on the page.  this prevents the reactjs app from working at all.  We are not asking you to unblock our analytics implementation (which is ONLY google analytics, we are not using any analytics using the hp.com domain, at least not on this site)  I have submitted a pull request to add the retail partner's site as a property with hp.com as an allowed resource for that domain.
the pr is https://github.com/disconnectme/disconnect-tracking-protection/pull/103#issue-332187602

the bug for the broken page is 
 https://github.com/webcompat/web-bugs/issues/43475#issue-514292451

**Comment by englehardt** [comment]
@patjack FYI the developer [found a fix](https://github.com/webcompat/web-bugs/issues/43475#issuecomment-548052822) for Firefox, so you may be able to close this.
