### ISSUE TITLE
Improper flagging of touchcommerce.com, inq.com, nuance.com

### ISSUE THREAD

**Issue by jourzero** [disconnectme/disconnect-tracking-protection#114]
Hello, the 3 TLDs mentioned in the title are not tracker domains. They are used by various online services for live chats with human agents (customer support use cases) and other similar purposes. Please remove these TLDs or at least be specific with FQDNs or subdomains that you perceive to be real trackers.

**Comment by disconnectme** [comment]
We see no evidence that these companies are misclassified.

**Comment by spirillen** [comment]
This post could have had more weight if OP actually knew anything about what a [TLD](https://www.mypdns.org/w/tld/) is...
