### ISSUE TITLE
Consider classifying id5-sync.com as a tracker

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#115]
Example page: https://libreriamo.it/

Request `https://id5-sync.com/k/155.gif?puid=` has a high-entropy cookie that includes UUIDs.
Redirects to `https://secure.adnxs.com/getuid?https://id5-sync.com/c/102/2/7/3.gif?puid=$UID&gdpr=0&gdpr_consent=`

ID5 appears to be a competitor to DigiTrust (see: https://clearcode.cc/blog/adtech-id-solutions/)

**Comment by patjack** [comment]
Thanks for flagging this! We verified and will be adding shortly.
