### ISSUE TITLE
ClickFrog origins aren't included in the Advertising category

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#116]
In the [tracker descriptions](https://github.com/disconnectme/disconnect-tracking-protection/blob/master/descriptions.md#ClickFrog) page you mention that ClickFrog origins are classified as both Advertising and Fingerprinting, however they only appear in the Fingerprinting category on the list.

**Comment by patjack** [comment]
Hi @englehardt - the ClickFrog entity (with various domains) is in both `Advertising` and `Fingerprinting` but the`clickfrog.ru` domain only appears in `Advertising`. It's possible that the`clickfrog.ru` domain should also appear in the `Fingerprinting` list too. I'll double check that and follow up.

**Comment by englehardt** [comment]
> the ClickFrog entity (with various domains) is in both `Advertising` and `Fingerprinting`

That doesn't seem to be the case, which was my motivation in filing this. The [clickfrog resources](https://github.com/disconnectme/disconnect-tracking-protection/blob/7fb7a4ee8d2cf8b9dbb7e2f0e8dd1b867e35e841/services.json#L10091-L10098.) (not `clickfrog.ru`) only appear in the Fingerprinting category.

**Comment by patjack** [comment]
Ah ok, I understand and that makes sense. We'll add those domains to`Advertising`.
