### ISSUE TITLE
Consider classifying origo.hu as a fingerprinter

### ISSUE THREAD

**Issue by birdsarah** [disconnectme/disconnect-tracking-protection#119]
Here is an example script which, to my eyes, includes fingerprintjs code: http://outal.origo.hu/js/1564578277216-80331/outa.min.js 

The subdomain `outal.origo.hu` is blocked on EasyPrivacy in their hungarian section: https://github.com/easylist/easylist/blob/d3f4b32bdee5e9b5ece37e4945288efd1ded3502/easyprivacy/easyprivacy_specific_international.txt#L652

Example sites hosting origo.hu script outa.min.js:
* https://accounts.freemail.hu/oauth/login
* https://videa.hu/
* https://greencottagediy.reblog.hu/

**Comment by patjack** [comment]
Hi @birdsarah - thanks for the detailed report! We'll investigate and if verified, we'll add it.
