### ISSUE TITLE
Horyzon Media's incorrect domains

### ISSUE THREAD

**Issue by Perdu** [disconnectme/disconnect-tracking-protection#120]
Hi,

We relied on the services.json list in a study to link tracking domains to company names.
We were contacted by the "Horyzon Media" company because their company appeared in our study as performing tracking on much more websites that they actually do.
According to them, they don't own smartadserver.com and  meetic-partners.com.
As I don't know how this list is constructed, I cannot verify this information.

Affected lines are:
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L3413

Cheers,

**Comment by patjack** [comment]
Hi @Perdu - thanks! We'll investigate and reclassify if needed.
