### ISSUE TITLE
Add ebaystatic.com to entity list?

### ISSUE THREAD

**Issue by birdsarah** [disconnectme/disconnect-tracking-protection#123]
In recent crawl work I found the domains ebaystatic.com and ebayimg.com as very prevalent. Should they be added to the entities list under ebay resources?

**Comment by llacb47** [comment]
Also add `ebaydesc.com`

`https://vi.vipr.ebaydesc.com/ws/eBayISAPI.dll?ViewItemDescV4&item=114290008523&t=0&category=21168&seller=51imperial&excSoj=1&excTrk=1&lsite=0&ittenable=true&domain=ebay.com&descgauge=1&cspheader=1&oneClk=2&secureDesc=1`

**Comment by gutmensch** [comment]
@birdsarah @patjack May I ask if this is the standard workflow for this project to just announce some domains as "very prevalent" (no real proof or described issues provided, no tracking pixel urls provided, no malicious other content provided) and then just execute blocking for *very obvious* static content domains (img and static in the name!), which basically disables css, images, fonts, etc. for millions of users? I am not advocating against the purpose of this project but I would like to seriously question the missing professionalism here. Especially looking at 32 open PRs not being looked at for months. Is this whole project even active or only a bad joke?

**Comment by birdsarah** [comment]
@gutmensch I don't think you understand the implications of adding a domain to the entities list. It often has counter-blocking effects as it allows multiple domains to be understood as all being from the same first-party, thereby allowing content that should work together to work together.

As a professional, I will refrain from responding to the rest of your comments. They are, at the least, off-topic for this issue.
