### ISSUE TITLE
Fingerprinting scripts from musthird.com are not blocked

### ISSUE THREAD

**Issue by UmarIqbal** [disconnectme/disconnect-tracking-protection#125]
Found musthird.com serving fingerprinting scripts in the wild. musthird.com is owned by https://www.markmonitor.com (looked up with whois record) and Disconnect does have markmonitor in analytics category. 

The live script from musthird.com can be seen at: http://ss.musthird.com/s.js . The script embedds fingerprintjs2 and there are clear cases of fingerprinting. 

Canvas fingerprinting snippet copied from the script:

```
function() {
    var g = [],
        i = document.createElement("canvas");
    if (i.getContext &&
        i.getContext("2d")) {
        i.width = 2E3;
        i.height = 200;
        i.style.display = "inline";
        var h = i.getContext("2d");
        h.rect(0, 0, 10, 10);
        h.rect(2, 2, 6, 6);
        g.push("canvas winding:" + (!1 === h.isPointInPath(5, 5, "evenodd") ? "yes" : "no"));
        h.textBaseline = "alphabetic";
        h.fillStyle = "#f60";
        h.fillRect(125, 1, 62, 20);
        h.fillStyle = "#069";
        h.font = "11pt Arial";
        h.fillText("Cwm fjordbank glyphs vext quiz, \ud83d\ude03", 2, 15);
        h.fillStyle = "rgba(102, 204, 0, 0.2)";
        h.font = "18pt Arial";
        h.fillText("Cwm fjordbank glyphs vext quiz, \ud83d\ude03", 4, 45);
        h.globalCompositeOperation =
            "multiply";
        h.fillStyle = "rgb(255,0,255)";
        h.beginPath();
        h.arc(50, 50, 50, 0, 2 * Math.PI, !0);
        h.closePath();
        h.fill();
        h.fillStyle = "rgb(0,255,255)";
        h.beginPath();
        h.arc(100, 50, 50, 0, 2 * Math.PI, !0);
        h.closePath();
        h.fill();
        h.fillStyle = "rgb(255,255,0)";
        h.beginPath();
        h.arc(75, 100, 50, 0, 2 * Math.PI, !0);
        h.closePath();
        h.fill();
        h.fillStyle = "rgb(255,0,255)";
        h.arc(75, 75, 75, 0, 2 * Math.PI, !0);
        h.arc(75, 75, 25, 0, 2 * Math.PI, !0);
        h.fill("evenodd");
        i.toDataURL && g.push("canvas fp:" + i.toDataURL());
        b.canvasFingerprint_ = t.MD5(g.join("~"))
    }
}
```

In our investigations with @englehardt , we found its presence on country specific airbnb websites such as airbnb.com, airbnb.de, airbnb.ie, airbnb.nl, airbnb.pl etc.

**Comment by patjack** [comment]
Hi @UmarIqbal - thanks for flagging this! According to the WHOIS, it appears `musthird.com` is owned by Airbnb and MarkMonitor the domain registrar:

> Domain Name: musthird.com
Registry Domain ID: 2187371020_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.markmonitor.com
Registrar URL: http://www.markmonitor.com
Updated Date: 2019-10-14T02:16:52-0700
Creation Date: 2017-11-14T14:41:55-0800
Registrar Registration Expiration Date: 2021-11-14T00:00:00-0800
Registrar: MarkMonitor, Inc.
Registrar IANA ID: 292
Registrar Abuse Contact Email: abusecomplaints@markmonitor.com
Registrar Abuse Contact Phone: +1.2083895740
Domain Status: clientUpdateProhibited (https://www.icann.org/epp#clientUpdateProhibited)
Domain Status: clientTransferProhibited (https://www.icann.org/epp#clientTransferProhibited)
Domain Status: clientDeleteProhibited (https://www.icann.org/epp#clientDeleteProhibited)
Registrant Organization: Airbnb, Inc.
Registrant State/Province: CA
Registrant Country: US
Admin Organization: Airbnb, Inc.
Admin State/Province: CA
Admin Country: US
Tech Organization: Airbnb, Inc.
Tech State/Province: CA
Tech Country: US
Name Server: ns-1197.awsdns-21.org
Name Server: ns-1992.awsdns-57.co.uk
Name Server: ns-537.awsdns-03.net
Name Server: ns-335.awsdns-41.com
DNSSEC: unsigned
URL of the ICANN WHOIS Data Problem Reporting System: http://wdprs.internic.net/
>>> Last update of WHOIS database: 2020-01-08T11:40:15-0800 <<<

The provided script url and snippet is definitely helpful and we'll add it to our review queue. I'll follow up if we have any questions. Thanks!

**Comment by kravietz** [comment]
Correctly detected as fingerprinting and JavaScript obfuscation here https://webcookies.org/cookies/ss.musthird.com/30305160

**Comment by a-privacy-conscious-user** [comment]
Blocked by AdGuard Tracking Protection filter ( https://filters.adtidy.org/extension/chromium/filters/3.txt )

![Captura de Pantalla 2020-06-30 a la(s) 12 25 18](https://user-images.githubusercontent.com/67610240/86145059-da7de580-bacc-11ea-9492-2a29ef594bad.png)
 
and also by EasyPrivacy ( https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers.txt )

![Captura de Pantalla 2020-06-30 a la(s) 12 26 29](https://user-images.githubusercontent.com/67610240/86145175-fda89500-bacc-11ea-9779-644f7159eaae.png)
