### ISSUE TITLE
Cbox updated to remove Fingerprinting

### ISSUE THREAD

**Issue by tomlove** [disconnectme/disconnect-tracking-protection#128]
The current version is at https://static.cbox.ws/jsc/jsc_10_1578558511.js

cbx.fp is hardcoded to 0 and there is no fingerprint code.

**Comment by englehardt** [comment]
@patjack FYI we're getting reports of breakage in Firefox due to this issue (https://bugzilla.mozilla.org/show_bug.cgi?id=1609857). Do you have you an expected timeline for re-reviewing cbox?

**Comment by slavserver** [comment]
Please view the error request as soon as possible. *.Cbox.ws is an integral part of the content for many sites ... tnx

**Comment by patjack** [comment]
Hi all - we re-reviewed cbox and will push an update shortly that removes cbox.ws from the fingerprinting category. Thanks!

**Comment by slavserver** [comment]
very tnx
