### ISSUE TITLE
Consider reclassifying rollick.io

### ISSUE THREAD

**Issue by wiriyan** [disconnectme/disconnect-tracking-protection#131]
We use our rollick.io domain to serve up Javascript code to our clients for their lead submission pages. Our domain is being flagged into the "Analytics" category and our Javascript is being blocked. Please consider removing our domain from the block. Thank you.

**Comment by disconnectme** [comment]
Based on our review of the privacy policy at https://gorollick.com/company/site-info/privacy-policy-terms-of-service/ it appears this domain is properly classified. In particular the section HOW WE COLLECT AND USE INFORMATION details the collection of data about particular devices and users in a third-party context. If you feel this determination is incorrect, please provide citations to language in your policy that supports your position that rollick.io is not a tracker as we define that term.
