### ISSUE TITLE
Removing reddit.com from being classed as a tracker.

### ISSUE THREAD

**Issue by ryanbr** [disconnectme/disconnect-tracking-protection#132]
We have had a few webcompat issues regarding user embedding reddit content on 3rd-party sites, We've been trying to fix embedded reddit.com items being loaded sites. None of the reddit urls seem to be using any obvious tracking.

Here is a sample of reddit issues I've been dealing with:

https://github.com/brave/adblock-lists/pull/320
https://github.com/brave/adblock-lists/pull/299
https://github.com/brave/adblock-lists/pull/287
https://github.com/brave/adblock-lists/pull/239
https://github.com/brave/adblock-lists/pull/89

Is it possible to remove or re-classify reddit.com domain?

**Comment by disconnectme** [comment]
Reddit's privacy policy seems to indicate proper classification. For example: 

"Information collected from integrations. We also may receive information about you, including log and usage data and cookie information, from third-party websites that integrate our Services, including our embeds, buttons, and advertising technology. For example, when you visit a website that uses Reddit embeds, we may receive information about the web page you visited. You can control how we use this information to personalize the Services for you by adjusting your preferences here."

In addition, the webcompat issues are not prevalent enough to support placing Reddit in the Content category at this time.

**Comment by llacb47** [comment]
Yes, they are prevalent enough. Fix the issue instead of ignoring it, please.
