### ISSUE TITLE
Removing pinpoll.com from being classed as a tracker

### ISSUE THREAD

**Issue by jfitzinger** [disconnectme/disconnect-tracking-protection#135]
[Pinpoll ](https://www.pinpoll.com/)provides:
- Solutions for Analytics and DMP = **Pinpoll DMP and Analytics** (domain: pa.pinpoll.com)
- _User Engagement Tools_ for publishers (polls, quizzes) = **Pinpoll Tools** (domain: tools.pinpoll.com)

We use fingerprinting for both products. In case of Pinpoll Tools (tools.pinpoll.com), fingerprinting is only used for **fraud prevention** (users trying to generate fake votes on polls). At the moment pinpoll.com is being blocked in FF because it is classified as a tracker using fingerprinting. As we only use fingerprinting for tracking on sub domain pa.pinpoll.com, could you please remove pinpoll.com from the list of trackers? The domain pa.pinpoll.com is used for tracking. Would we have to move tracking to a different top-level domain?

**Comment by llacb47** [comment]
fraud prevention uses fingerprinting, no?

**Comment by jfitzinger** [comment]
Fraud prevention uses fingerprinting, but only  in case a user votes on a poll. So only in case of user interaction in a purposeful GDPR compliant manner.  That is the reason why we cannot remove the fingerprinting library immediately.

**Comment by disconnectme** [comment]
Resolved. https://github.com/disconnectme/disconnect-tracking-protection/commit/45154a89b88f5057ac973637043afe6320b7bf66#diff-f5fb0346ca2de022483b15e81d888f18

Temporarily removed from Fingerprinting based on verification that fingerprinting code was removed.
