### ISSUE TITLE
Consider adding multicloud-ibm.com to IBM's entity

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#136]
In [Bug 1610431](https://bugzilla.mozilla.org/show_bug.cgi?id=1610431) we received a report of breakage on multicloud-ibm.com. Multi cloud is an [IBM product](https://www.ibm.com/cloud/multicloud-manager), so this domain might be owned by IBM.

**Comment by englehardt** [comment]
[Bug 1610428](https://bugzilla.mozilla.org/show_bug.cgi?id=1610428) gives more details. It seems that `ibm.com` is the embedded resource and `multicloud-ibm.com` is the property.

**Comment by nalraajan** [comment]
thank you for looking this issue. Any updates on this issue? What will be the fix of this issue?

**Comment by nalraajan** [comment]
any updates on this issue?

**Comment by disconnectme** [comment]
Thanks for the heads up. We will be adding `multicloud-ibm.com` to the IBM entity shortly.
