### ISSUE TITLE
Consider adding ie8eamus.com as fingerprinting 

### ISSUE THREAD

**Issue by UmarIqbal** [disconnectme/disconnect-tracking-protection#140]
ie8eamus.com serves fingerprinting scripts on several websites.The live version of the scripts contains the fingerprinting code at: https://ie8eamus.com/sfp.js

The script is obfuscated but it makes several JavaScript API calls that are used for fingerprinting:
```
WebGLRenderingContext.attachShader
WebGLRenderingContext.bindBuffer 
WebGLRenderingContext.bufferData 
WebGLRenderingContext.clear
WebGLRenderingContext.clearColor
WebGLRenderingContext.compileShader
WebGLRenderingContext.createBuffer
OfflineAudioContext.destination
OfflineAudioContext.currentTime
window.navigator.platform
window.navigator.oscpu
window.navigator.languages
```

Some websites on which the script from ie8eamus.com is embedded:
```
https://oload.info
https://saump3.com/
https://www.letmewatchthis.fun/
http://javtorrent.re/
https://vercomicsporno.com/
```

**Comment by patjack** [comment]
Thanks for submitting this for review with the included API calls and example websites. We've verified and will add shortly.

**Comment by patjack** [comment]
Added: https://github.com/disconnectme/disconnect-tracking-protection/commit/36ce842065f1a2d07a7c838c3776d31099073d17
