### ISSUE TITLE
Consider adding ad-score.com as fingerprinting 

### ISSUE THREAD

**Issue by UmarIqbal** [disconnectme/disconnect-tracking-protection#141]
ad-score.com serves fingerprinting scripts on several websites. ad-score.com is already present in advertising category of the list. The live version of the script is available at: https://js.ad-score.com/score.min.js?pid=1000449

The script is obfuscated but it makes several JavaScript API calls that are used for fingerprinting:

```
window.navigator.doNotTrack
window.navigator.geolocation
window.navigator.language
window.navigator.onLine
CanvasRenderingContext2D.drawImage
CanvasRenderingContext2D.fill
CanvasRenderingContext2D.fillRect
CanvasRenderingContext2D.getImageData
```

Some websites on which the script from ad-score.com is embedded:

```
https://www.realclearhistory.com/
https://mutually.com/
https://www.ecr.co.za/
```

**Comment by patjack** [comment]
Thanks for submitting this for review with the included API calls and example websites. We've verified and will add shortly.
