### ISSUE TITLE
Consider adding bounceexchange.com as fingerprinting 

### ISSUE THREAD

**Issue by UmarIqbal** [disconnectme/disconnect-tracking-protection#143]
bounceexchange.com serves fingerprinting scripts on several websites. bounceexchange.com is already present in advertising category of the list. The live version of the script is available at: https://assets.bounceexchange.com/assets/smart-tags/versioned/ijs_all_modules_cjs_min_151c6d988cc47fd18d97ec183433e61d.js

The script makes several JavaScript API calls that are used for fingerprinting:

```
RTCPeerConnection.createDataChannel
RTCPeerConnection.createOffer
RTCPeerConnection.setLocalDescription
RTCPeerConnection.iceGatheringState
RTCPeerConnection.onicecandidate
window.navigator.buildID 
window.navigator.cookieEnabled
window.navigator.doNotTrack 
window.navigator.language
window.navigator.languages 
window.navigator.oscpu 
window.navigator.platform 
window.navigator.productSub
```

Some websites on which the script from bounceexchange.com is embedded:
```
https://www.optimum.net/
https://www.sears.com/
https://dailycaller.com/
https://www.barneys.com/
https://www.shoesforcrews.com/
```

**Comment by patjack** [comment]
Thanks for submitting this for review with the included API calls and example websites. We've verified and will add shortly.

**Comment by spirillen** [comment]
You should update the relation with `wunderkind.co`

  - See details at <https://www.mypdns.org/T2546>
