### ISSUE TITLE
Consider Removing MediaMath from Fingerprinting list

### ISSUE THREAD

**Issue by elamy-mm** [disconnectme/disconnect-tracking-protection#150]
MediaMath.com
Mathtag.com

For the cited Policy Review items:

1. Tactads technology has been deprecated from the MediaMath platform for a number of years.
2. The quoted language from the Privacy Policy is out of date - current Privacy Policy has no reference to Fingerprinting or cookieless tracking technology and this technology is no longer employed.

For cited Technical Review items:

1. All fingerprinting technology (inclusive of cited font-based code) has been removed.
2. All fingerprinting technology (including cited device-property based code) has been removed.

**Comment by ryanbr** [comment]
`Mathtag.com` still considered a tracker, and will remain in Easyprivacy, keeping this domain listed as a tracker should remain.

**Comment by disconnectme** [comment]
MediaMath was temporarily removed from fingerprinting category based on removal of fingerprinting code. https://github.com/disconnectme/disconnect-tracking-protection/commit/0779bf2f14c56eb07d4a5e05ec3689e6f6e7f3c7

MM remains on tracking list.
