### ISSUE TITLE
Consider removing poool.fr from Analytics & Fingerprinting categories

### ISSUE THREAD

**Issue by dackmin** [disconnectme/disconnect-tracking-protection#152]
Hi guys!

As stated in PR #151, we **used** to generate fingerprint for users to track the number of articles users could unlock in a row, but removed any code generating, transmitting or referencing user fingerprint, and replaced fingerprints with a single basic first party cookie.

We are not an advertising company. 
Please consider accepting our PR and removing poool.fr from Disconnect's Tracking list.

Thanks,
Ugo, CTO @p3ol

**Comment by dackmin** [comment]
any news on this? @patjack @disconnectme

**Comment by patjack** [comment]
Closed w/commit https://github.com/disconnectme/disconnect-tracking-protection/commit/6410e1d5fe1cca3ac317f21ce6fccc139d641bb4. Thanks!
