### ISSUE TITLE
Consider removing rambler.ru from the tracking

### ISSUE THREAD

**Issue by ryanbr** [disconnectme/disconnect-tracking-protection#157]
There is some tracking subdomains being used which we are blocking in Easyprivacy: `||ssp.rambler.ru^` and `||sync.rambler.ru^`. But blocking the entire domain rambler.ru is a bad idea. It is used for authing, comments.

Example, visiting https://www.gazeta.ru/ and https://www.championat.com/ (and other rambler.ru related sites) will cause the css/images to be blocked.

We've been attempting to fix this via whitelisting to get around the block:

https://github.com/brave/adblock-lists/pull/330

Can we reconsider this block on `rambler.ru` ?

**Comment by disconnectme** [comment]
Rambler seems to be properly classified based on technical and policy review. There seem to be many Rambler subdomains and the TLD collecting user data. In this case it does not seem the potential privacy harm is outweighed by usability issues.
