### ISSUE TITLE
 Consider removing browser-update.org from the list

### ISSUE THREAD

**Issue by josselex** [disconnectme/disconnect-tracking-protection#160]
Browser-update.org is not tracking users in any way. Therefore please remove it from the list.

Browser-update.org is an open source project, to infrom about insecure and unsupported outdated browsers. 
No identifying cookie is set, see 
https://github.com/browser-update/browser-update/wiki/Privacy

The only cookie set always has the value `browserupdateorg=pause` and is justed used to show a message once per visitor in order not to annoy visitors to much.

**Comment by ryanbr** [comment]
We've denied this request in Easyprivacy (which was also in uBO). https://github.com/uBlockOrigin/uAssets/issues/7084

**Comment by krystian3w** [comment]
`https://updatemybrowser.org/widget`

**Comment by josselex** [comment]
> 
> 
> We've denied this request in Easyprivacy (which was also in uBO). [uBlockOrigin/uAssets#7084](https://github.com/uBlockOrigin/uAssets/issues/7084)

Just quoting myself what I worte there for further explanation:

> But we are not tracking.
> 
>     The cookie is the same for all users. It has no specific information. it just says: browserupdateorg=pause.
>     So we can not identify users in any way.
>     The cookie only lasts 24 hours by default. It is only set to the current domain. We cannot track in any way across domains. It is just used to show a message only once per user and 24hours.
>     We do not record data except for a random sample of the browser used for every 1000th user. This can not be used in any way to track anybody. You can check the script to verify this.
> 
> Please, if you say it's tracking, say why or what your definition is.

**Comment by josselex** [comment]
We completely removed the collection of the statistics on the used browser. (It already was completely anonymous and only collect edfor only every 1000th user).
You can see it in this commit here: 0723245868fcd45b58fba17a0496c0a673a9af0e.

Now please remove us from the privacy list as we do not record any data or store any cookie that can identify a user.

**Comment by disconnectme** [comment]
Domain appears to be properly classified as tracker as defined here. From technical perspective script sets cookies, receives user/device data on third-party sites. From policy perspective, does not appear to be legally enforceable or include complete description of data practices.
