### ISSUE TITLE
List of blocks missing from your blocklist

### ISSUE THREAD

**Issue by Redback813** [disconnectme/disconnect-tracking-protection#161]
Have a list of blocks from my dnsmasq logs over the last 6months that are still that are still active.
[Blacklist.txt](https://github.com/disconnectme/disconnect-tracking-protection/files/4333993/Blacklist.txt)

**Comment by disconnectme** [comment]
Many of these have been added since this issue. Some are CNAMES for other domains that already exist on our list. Thank you for creating this issue.
