### ISSUE TITLE
Please consider removing (Stacktrack)stat-track.com as a Fingerprinter.

### ISSUE THREAD

**Issue by gentgaashi** [disconnectme/disconnect-tracking-protection#163]
Hi all,

It has come to our attention that stat-track.com was classified as a Fingerprinter because it was referencing a redundant library that we were using.

The script was used to create a unique user id so that no other personal information was stored and captured. However, that beacon and the data it produces was never used. In fact, we have disabled that beacon and it should no longer get deployed on any traffic. Overall, that domain is part of Moosend.com and implements various types of subscription forms for websites (https://moosend.com/subscription-forms/).

Could you re-consider your classification please?

Thanks

**Comment by ryanbr** [comment]
Was requested in Easyprivacy also: https://github.com/easylist/easylist/issues/5102

**Comment by disconnectme** [comment]
Temporarily removed based on removal of fingerprinting code. Remains on tracker list. https://github.com/disconnectme/disconnect-tracking-protection/commit/5e0cedd7bc5c700528a2c393febcc389544c6684
