### ISSUE TITLE
The Google entity is missing blogspot.com as a property

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#164]
The `Content` category contains `blogger.com` and the entitylist contains `blogger.com` as both a Google property and resource. However, the Google entity does not contain `blogspot.com` as a property. This has led to breakage in Firefox (see [Bug 1620530](https://bugzilla.mozilla.org/show_bug.cgi?id=1620530)). From what I can tell, Blogspot is owned by Google.

**Comment by patjack** [comment]
@englehardt thanks for the heads up. Pushing this shortly.
