### ISSUE TITLE
snplow.net (Snowplow Analytics)

### ISSUE THREAD

**Issue by kravietz** [disconnectme/disconnect-tracking-protection#168]
https://snowplowanalytics.com/privacy-policy/

> When you visit our website, https://snowplowanalytics.com and other subdomains owned and run by Snowplow Analytics Limited (company number 07852221 with registered office is at The Rome Building, 32-38 Scrutton Street, London, EC2A 4RQ, United Kingdom), we track:
> 
>     The following personal-identifiable information about you:
>         your IP address and
>         your device (cookie ID).
>         For users who submit their email address via our webforms (e.g. to sign up to a demo or ask or answer ask a question on our forums) we also track the information submitted in those forms e.g. your name and email address, the question you have asked or the answer you have given.

Cookies & domains https://webcookies.org/cookie/domain/com-rypl-main.collector.snplow.net/1803592

**Comment by patjack** [comment]
Thank you for filing this issue! We are in the process of verifying and will update when we have completed review.
