### ISSUE TITLE
Relation between services.json and simple_ad.txt and simple_tracking.txt

### ISSUE THREAD

**Issue by makruiten** [disconnectme/disconnect-tracking-protection#171]
Hi,

I noticed that many host based tracking blockers use Disconnect.me filter lists that are hosted on Amazon AWS:

- https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
- https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
- https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
- https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt

I've compared the Advertisements and Analytics categories from services.json to simple_ad.txt and simple_tracking.txt and there is a huge difference. Are those still being maintained and why are those different from the services.json file on this repository?

**Comment by disconnectme** [comment]
Services.json is the up to date version of our tracker protection list.
