### ISSUE TITLE
Remove simply.com

### ISSUE THREAD

**Issue by emilstahl** [disconnectme/disconnect-tracking-protection#173]
Hi

We acquired Simply.com, Simply.net and other domains, see https://domaininvesting.com/unoeuro-announces-rebrand-to-simply-com/

The name is now used for a web hosting brand, and not an affiliate or ad company. We are not doing tracking. I know that the domain is listed since it was an affiliate network/serving tracking in the past, but since the domain has changed owners and purpose, can you please remove it from your list? Thanks!

**Comment by spirillen** [comment]
Hey Emil, I can only find `simply.com` on the page you link to

Beside that there is a huge number of trackers running on your site, which obliviously isn't adding trust to your domain

> We are not doing tracking. 

Shall we have a look on that statement?

```
||maxmind.com/js/device.js$3p
||ads-twitter.com^$3p
||digitaladvisor.dk^$3p
https://trk.teamblue.services/js/trk_standalone.js
||facebook.net^$script
||google-analytics.com/analytics.js
||googletagmanager.com/gtm.js$script
||googleapis.com^$important
```

And from third parties I find equivalents in history and to present

```
static.simply.com (fademind_add_risk/domain.list:trk.simply.net) (fademind_extras/domain.list:trk.simply.net)
```

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +3 | \|\|maxmind.com/js/device.js$3p | -- | `www.simply.com` | 3 | script | `https://device.maxmind.com/js/device.js` |
| +2 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/simply-favicon-96px.png` |
| +2 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/simply-favicon-96px.png` |
| +2 | `##[href^="https://www.facebook.com"]` |  | `www.simply.com` |  | dom | `https://www.simply.com/dk/` |
| +2 | ##.cookie-alert |  | `www.simply.com` |  | dom | `https://www.simply.com/dk/` |
| +2 | ###cookie-warning |  | `www.simply.com` |  | dom | `https://www.simply.com/dk/` |
| +1 |  |  | `www.simply.com` | 1 | font | `https://static.simply.com/assets/build/f538891c3a8dc7e206fd7a7fbb66ebb5.woff` |
| +1 |  |  | `www.simply.com` | 1 | font | `https://static.simply.com/assets/build/ddad15b5c1b7359d9d38363f01b58987.woff2` |
| +1 |  |  | `www.simply.com` | 1 | font | `https://static.simply.com/assets/build/35fd7cacd394b3837eee881f8f6456df.woff2` |
| +1 |  |  | `www.simply.com` | 1 | font | `https://static.simply.com/assets/build/0ffa8f97ca92f387e47fa4719d27a5a5.woff2` |
| +1 |  |  | `www.simply.com` | 1 | font | `https://static.simply.com/assets/build/c46f5c3c07d96b6cf2b6031f6ef203d3.woff2` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/4f5f456f4d5e5bdab0759efead2e26b1.svg` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/ba1c7f5df0dd4173c951a644c65e02df.svg` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/f4e8fc5376a202f1d771ff93fab6b2ea.svg` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/73f6bbe574f52c1a3934afe379ff2849.svg` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/0274b0cae487162ec17e267b81295303.svg` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/2466595d33e66f85d58ae4d4cae9252b.png` |
| +1 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/build/f86f7b32037078d32f22f10dd800208b.gif` |
| +1 | \|\|ads-twitter.com^$3p | -- | `www.simply.com` | 3 | script | `https://static.ads-twitter.com/uwt.js` |
| +1 | \|\|digitaladvisor.dk^$3p | -- | `www.simply.com` | 3 | script | `https://script.digitaladvisor.dk/lp/gGr15im` |
| +1 | /js/trk_ | -- | `www.simply.com` | 3 | script | `https://trk.teamblue.services/js/trk_standalone.js` |
| +1 | \|\|facebook.net^$script | -- | `www.simply.com` | 3 | script | `https://connect.facebook.net/en_US/sdk.js` |
| +1 | \|\|facebook.net^$script | -- | `www.simply.com` | 3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +1 | google-analytics.com/analytics.js | << | `www.simply.com` |  | script | `https://www.google-analytics.com/analytics.js` |
| +1 | \|\|google-analytics.com/analytics.js | -- | `www.simply.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +1 | googletagmanager.com/gtm.js | << | `www.simply.com` |  | script | `https://www.googletagmanager.com/gtm.js?id=GTM-TZV8MD` |
| +1 | \|\|googletagmanager.com/gtm.js$script | -- | `www.simply.com` | 3 | script | `https://www.googletagmanager.com/gtm.js?id=GTM-TZV8MD` |
| +0 | \|\|digitaladvisor.dk^$3p | -- | `www.simply.com` | 3 | script | `https://script.digitaladvisor.dk/lp/gGr15im` |
| +0 | /js/trk_ | -- | `www.simply.com` | 3 | script | `https://trk.teamblue.services/js/trk_standalone.js` |
| +0 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/simply-logo-white.svg` |
| +0 |  |  | `www.simply.com` | 1 | image | `https://static.simply.com/assets/simply-logo-color.svg` |
| +0 | \|\|facebook.net^$script | -- | `www.simply.com` | 3 | script | `https://connect.facebook.net/en_US/sdk.js` |
| +0 |  |  | `www.simply.com` | 1 | script | `https://static.simply.com/assets/build/late.js?_r=567` |
| +0 |  |  | `www.simply.com` | 1 | script | `https://static.simply.com/assets/build/defer.js?_r=567` |
| +0 |  |  | `www.simply.com` | 1 | script | `https://static.simply.com/assets/build/app.js?_r=567` |
| +0 |  |  | `www.simply.com` | 1 | css | `https://static.simply.com/assets/build/bundle.css?_r=567` |
| +0 | \|\|googleapis.com^$important | -- | `www.simply.com` | 3 | css | `https://fonts.googleapis.com/css?family=Nunito+Sans:300,300i,400,400i,700,700i&display=swap` |
| +0 |  |  | `www.simply.com` | 1 | doc | `https://www.simply.com/dk/` |
| +0 |  |  | `www.simply.com` | 1 | doc | `https://www.simply.com/` |
| +0 |  |  | simply.com | 1 | doc | `http://simply.com/` |
</details>

**Comment by disconnectme** [comment]
As communicated via email on June 22, 2020: We base our decisions on publicly available information so it would be great if you could send specific citations from your privacy policy supporting your position that http://Simply.com should not be classified as a tracker. 

The most efficient way to be removed from the list is to make a legally binding commitment in your privacy policy like the following and resolve any inconsistencies it may have with existing policy language. 

“Nothing in this policy contradicts the following statement: http://Simply.com does not collect, retain or share any data regarding a particular user or device (including IP addresses and user identifiers) on sites or apps not owned by http://Simply.com/COMPANY.”
