### ISSUE TITLE
Update Google Entity with Missing Properties

### ISSUE THREAD

**Issue by Brandr0id** [disconnectme/disconnect-tracking-protection#174]
**pinpoint-dot-chromeperf.appspot.com** is Google's perf web portal and should be added to the entities.json definition for Google. Currently without this the following breakage can occur:

Example https://pinpoint-dot-chromeperf.appspot.com/job/165a7039e20000:
![image](https://user-images.githubusercontent.com/18271690/81130425-8e635a00-8efc-11ea-8c2c-a680800a9f23.png)

For good measure we should also probably add **googlesource.com** to the list of Google properties.

**Comment by Brandr0id** [comment]
@patjack fyi.

**Comment by patjack** [comment]
@Brandr0id thanks for flagging. We'll push an update shortly.
