### ISSUE TITLE
Consider removing Mailchimp from the list

### ISSUE THREAD

**Issue by ryanbr** [disconnectme/disconnect-tracking-protection#175]
We've had another report of breakage regarding blocks on mailchimp (which is used for web signups and forms) Can we get this domain removed from being blocked?

Example page: `https://nocsok.com/about` (from a recent report: https://github.com/brave/brave-browser/issues/9656)

We've created whitelists previously to get around blocks on mailchimp:
https://github.com/brave/adblock-lists/pull/202
https://github.com/brave/adblock-lists/pull/359

**Comment by disconnectme** [comment]
MailChimp seems to clearly fit the definition of a tracker, please see passages from its Cookie Statement (https://mailchimp.com/legal/cookies/) below.

There was a way to integrate MailChimp on a website with zero tracking, prior to the user submitting their email. I can't find a solid link to that right now. 

On balance, the privacy harm of allowing MailChimp to track is not outweighed by the breakage of breaking certain MailChimp popups. 

"
Member sites
If a Member elects to use certain Mailchimp add-ons or features, the use of those may permit or require additional cookies or tracking technologies to be employed. If a Member connects his or her website or e-commerce store (in each case, a “Site”) to a Mailchimp account, Mailchimp installs a JavaScript tracking snippet (“Snippet”) on that Member’s Site. This Snippet will allow cookies, pixels, and other technologies to be set on that Member’s Site to facilitate the use of certain automations, features and functionality offered by Mailchimp through the Service. The specific cookies, pixels, or other technologies that will be set on a Member’s Site depend on the particular add-ons or features that the Member chooses to use as part of the Service. End users should therefore review the relevant Member’s privacy notice and cookie disclosures for further information about the specific types of cookies and other tracking technologies used on the Site. These optional add-ons and features include:

Google remarketing ads: Our Google remarketing ads feature (also known as web retargeting ads) allows our Members to create and manage advertisements on the Google Display Network. When a Member elects to use this feature, Mailchimp installs a Google tracking pixel on that Member’s Site through the Snippet. The Snippet also allows that Member’s Site to set a Mailchimp cookie that will recognize Site end users via ads placed with the Google remarketing ads feature. These technologies facilitate the placement of advertising campaigns on the Google Display Network and enable Mailchimp to provide reporting to our Members about the performance of these advertising campaigns. To refuse these cookies, please follow the instructions below under the heading “How can I control cookies?” Alternatively, please click on the relevant opt-out link here:https://www.google.com/settings/ads/plugin

Facebook ads (including Facebook remarketing ads): Our Facebook ads feature allows our Members to display ads to their end users and others within the Facebook platform. When a Member elects to use this feature, Mailchimp installs a Facebook tracking pixel on that Member’s Site through the Snippet. The Snippet may also allow that Member’s Site to set a Mailchimp cookie that will recognize Site end users via ads placed with the Facebook ads feature. These tracking technologies facilitate the placement of advertising campaigns on the Facebook platform and enable Mailchimp to provide reporting to our Members about the performance of these advertising campaigns. Facebook does not provide an opt-out link for its cookies. For more information about Facebook cookies, please click here: https://www.facebook.com/policies/cookies/. To refuse these cookies, please follow the instructions below under the heading “How can I control cookies?”

Product retargeting emails: Our product retargeting emails feature allows our Members to promote new items or best sellers to their end users. When an end user clicks a link within a product retargeting email, the Member’s Site drops a Mailchimp cookie on that end user’s device that is placed through the Snippet. This cookie allows Mailchimp to track attribution rates and browser activity and provide reporting to the Member regarding the success of their product retargeting emails. To refuse this cookie, please follow the instructions below under the heading “How can I control cookies?”

Popup forms: The Snippet will allow a Member’s Site to deploy a Mailchimp cookie that recognizes whether an end user to that Member’s Site has previously viewed a popup form and ensures the same end user does not see the form again for a period of up to one year. To refuse this cookie, please follow the instructions below under the heading “How can I control cookies?”

Landing Pages and Websites
If a Member elects to use the Mailchimp features known as “Landing Pages” or “Websites,” the use of either feature will permit additional cookies or tracking technologies to be employed by the Member. Members who create Landing Pages or Websites will have the option to set cookies on the device of any end user to those pages. When a Member chooses to set cookies, Mailchimp installs the Snippet on that Member’s Landing Page or Website to facilitate the deployment of the cookie(s) selected by that Member. The specific cookies, pixels, or other technologies that will be set on a Member’s Landing Page or Website depend on the particular add-ons or features that the Member chooses to use as part of the Service. End users should review the relevant Member’s privacy notice and cookie disclosures for further information about the specific types of cookies and other tracking technologies used on any Landing Page or Website. These optional add-ons and features include:

Track with Mailchimp: Our Track with Mailchimp feature allows Members to track unique visits by installing a tracking snippet on that Member’s Landing Page or Website through the Snippet. Track with Mailchimp calculates the conversion rate by comparing the number of unique visits to the number of end users who subscribe.

Facebook Pixel: Our Facebook Pixel feature allows our Members to track page views and create more targeting Facebook ads. When a Member elects to use this feature, Mailchimp installs a Facebook tracking pixel on that Member’s Landing Page or Website through the Snippet. The Snippet may also allow that Member’s Landing Page or Website to set a Mailchimp cookie that will recognize end users on Facebook via the Facebook ads feature. These tracking technologies facilitate the placement of advertising campaigns on the Facebook platform and enable Mailchimp to provide reporting to our Members about the performance of these advertising campaigns. Facebook does not provide an opt-out link for its cookies. For more information about Facebook cookies, please click here: https://www.facebook.com/policies/cookies/. To refuse these cookies, please follow the instructions below under the heading “How can I control cookies?”

Google Analytics: Our Google Analytics feature allows our Members to connect their Google Analytics Account to better understand their end users. When a Member elects to use this feature, Mailchimp installs a Google tracking pixel on that Member’s Site through the Snippet.
"
