### ISSUE TITLE
Consider removing liveperson.com (webchat/communication platform)

### ISSUE THREAD

**Issue by ryanbr** [disconnectme/disconnect-tracking-protection#176]
Liveperson is used for webchat between customers and businesses, blocking this domain will prevent users from communicating with businesses. Blocking at of these scripts used will prevent chat dialog box from showing.

The domain (.com and .net) is used on  `https://www.lowes.com/` and `https://www.darphin.com/`, and a few more: https://publicwww.com/websites/%22liveperson.com%22/

**Comment by disconnectme** [comment]
Liverperson privacy policy indicates proper classification, for example: "2. What information do we collect from you?
If you engage with a brand that uses our Services, we may collect: Chat and messaging transcripts on behalf of the brand,
Information on behalf of and/or requested by the brand, such as information related to your browsing, purchasing and online behavior and activities, and Automatic information, such as IP address, operating system and type of device used." In addition, there is no limit on retention of information. On balance at this time, the privacy harm seems to outweigh moving Liveperson to Content.
