### ISSUE TITLE
Consider moving reddit.com to the Content category

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#177]
Reddit's domain seems to be used to serve a bunch of content. We've seen a bunch of breakage from it over the years. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1628157 and the dependent bugs.

**Comment by disconnectme** [comment]
Reddit's privacy policy seems to indicate proper classification. For example: 

"Information collected from integrations. We also may receive information about you, including log and usage data and cookie information, from third-party websites that integrate our Services, including our embeds, buttons, and advertising technology. For example, when you visit a website that uses Reddit embeds, we may receive information about the web page you visited."

In addition, the webcompat issues are not prevalent enough to support placing Reddit in the Content category at this time.
