### ISSUE TITLE
Please unblock https://www.tchibo.de/

### ISSUE THREAD

**Issue by flbaue** [disconnectme/disconnect-tracking-protection#178]
Tchibo is a major German shop for coffee and fashion. Currently it is completely blocked.

**Comment by disconnectme** [comment]
Based on privacy policy classification appears to be correct. 

![image](https://user-images.githubusercontent.com/698691/88334965-6a3b3c00-cce7-11ea-8980-4859b97cab56.png)

**Comment by flbaue** [comment]
Sorry but this is nonsense. Blocking tchibo.de is like blocking amazon.de. Yes they use tracking tools and I hope you block those, but the main page itself is a major retailer.

**Comment by fmarier** [comment]
> Blocking tchibo.de is like blocking amazon.de.

`amazon.de` is also blocked: https://github.com/disconnectme/disconnect-tracking-protection/blob/eea6910d396923dd9dceb1ce9de2241a3055a6e4/services.json#L1210

**Comment by disconnectme** [comment]
Just to clarify both Amazon and Tchibo are blocked in third-party context only. Users with our protection are still able to visit these sites as normal, but will be protected from these domains collecting information when they visit other sites not owned by Tchibo and Amazon.

**Comment by krystian3w** [comment]
so time to block `allegro.pl` - have gemius / adocean etc.
