### ISSUE TITLE
Consider removing GoSquared.com as it blocks the GoSquared Chat widget

### ISSUE THREAD

**Issue by russellvaughan** [disconnectme/disconnect-tracking-protection#180]
Hello! My name is Russell Vaughan and I'm a Sales Engineer at GoSquared. A client had raised that you block our chat widget as it is loaded from gosquared.com, which is listed in your blacklist.

Our chat widget is not reliant on our Analytics tracking. If you block just our tracking endpoints, opposed to all of gosquared.com, our chat widget will still load and be functional. However, all tracking will still be blocked. We've worked with most of the other tracking blocking tools to solve this.

Could we ask that you use `data.gosquared.com` and `data2.gosquared.com` for your blacklist opposed to gosquared.com?

Please do let me know if you have any questions or need anything further.

**Comment by disconnectme** [comment]
We base our decisions on publicly available information so we require specific commitments in your privacy policy supporting your position that the GoSquared top level domain should not be classified as a tracker. 

Based on our review of your privacy policy it appears classification is proper. For example:

“GoSquared collects the following information from each visitor browsing your site:

    Their web browser: which browser they use & its version.
    Their platform: Whether they are using a desktop computer, a mobile phone, or a tablet device.
    Their operating system: which operating system they are running on their device & its version.
    IP address: the IPv4 and/or IPv6 address from which they are accessing your site.
    Their location: This is inferred from the IP address, and can indicate which city and country they are located at.
    The page they are viewing: the URL, title and path of the page they are viewing is used to determine your most popular pages and content.
    The pages they have viewed during their session: the URL, title and path of the pages they have visited whilst on your site. This is used for showing the journey of individual visitors on your website.
    The language setting of the browser. This is for reporting the languages and locales of your visitors.”
