### ISSUE TITLE
ThreatMatrix Port Scan Domain Names

### ISSUE THREAD

**Issue by ilikenwf** [disconnectme/disconnect-tracking-protection#182]
Info:
https://www.bleepingcomputer.com/news/security/list-of-well-known-web-sites-that-port-scan-their-visitors/

gorhill is working on something to protect IANA reserved IP addresses in uBlock Origin, but these domains should be considered for inclusion. I think we already have the top level one, but not necessarily all of these:

https://docs.google.com/spreadsheets/u/1/d/1Nu4lpyZ5PQUIpiLJBddXnr67t5-1y0u40dzyzSYj1gc/preview

**Comment by ilikenwf** [comment]
...I use uBO and so while I realize that covering the TLD covers all these, I thought it worth metnioning here.

**Comment by disconnectme** [comment]
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L5031

**Comment by spirillen** [comment]
Is it possible that someone could re-post that ugly doc somewhere safer (privacy) than on foofle?
