### ISSUE TITLE
Received promotional email; flocktory tracker not blocked

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#184]
Copying this unblocked tracker report over from [Bug 1641556](https://bugzilla.mozilla.org/show_bug.cgi?id=1641556). I have not investigated it myself.

```
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:76.0) Gecko/20100101 Firefox/76.0

Steps to reproduce:

Visited Megafon website (https://moscow.megafon.ru/), having Strict Protection Level set to "on".

Actual results:

After couple of hours I received a promotional email from 220-volt.ru@flocktory.com that states that I received a gift in 220-volt.ru internet shop from the Megafon.

I checked, Megafon website makes several calls to a https://api.flocktory.com which is clearly a tricking website.

Expected results:

I would like to have flocktory.com blocked in Strict Protection Level.
```

**Comment by dbolotin** [comment]
Hi! Just a polite notice. I reported a problem 15 days ago and it still left without attention. Is there a formal process that such issues go through? I am asking because this database seems very important to me, and the feature of Firefox browser relying on this repo is one of the main things why I am using it. Transparency of the process of inclusion and exclusion of tracking services is extremely important.

**Comment by spirillen** [comment]
@dbolotin try with a MR|PR  it might get higher attention :thinking: :thought_balloon:

**Comment by dbolotin** [comment]
Thanks for suggestion!

**Comment by patjack** [comment]
@dbolotin thanks for submitting and following up. We are reviewing this and will report back shortly. Creating issues, like this, are best for submitting potential trackers to us for review.

**Comment by dbolotin** [comment]
@patjack Thank you for your reply! I would gladly make a PR, but I see that each of them has a more or less formal description of the evidence for inclusion. Unfortunately I failed to find the list of criteria for inclusion of a document describing the process.
