### ISSUE TITLE
firefox strict rule trigger cloudflare sites captcha

### ISSUE THREAD

**Issue by dennyhalim** [disconnectme/disconnect-tracking-protection#188]
enabling firefox strict rule suddenly causes lots of websites using cloudflare give me captcha.

it seems the cloudflare javascript challenge gets blocked and cause it to move up the challenge to chaptcha.

rgds,
dny

**Comment by disconnectme** [comment]
Thanks unfortunately blocking all third-parties that we classify as trackers causes this and other breakage.
