### ISSUE TITLE
Consider adding Datadome as fingerprinter

### ISSUE THREAD

**Issue by ghost** [disconnectme/disconnect-tracking-protection#190]
You can find it for example on the nytimes.com and other websites as well. It has been identified as fingerprinter by Privacy Possum ( https://github.com/cowlicks/privacypossum )

![Captura de Pantalla 2020-06-29 a la(s) 18 48 29](https://user-images.githubusercontent.com/67610240/86059835-eff5ff80-ba39-11ea-9031-1ebc1131e3e7.png)

I attach data from DuckDuckGo tracker radar ( https://github.com/duckduckgo/tracker-radar ) which shows the excessive amount of APIs it uses so as to confirm that Datadome is indeed a fingerprinter tracker

![Captura de Pantalla 2020-06-29 a la(s) 18 54 50](https://user-images.githubusercontent.com/67610240/86059932-27fd4280-ba3a-11ea-946c-cb12c5a9aad9.png)

![Captura de Pantalla 2020-06-29 a la(s) 18 55 02](https://user-images.githubusercontent.com/67610240/86059942-2af83300-ba3a-11ea-8b29-7c8bb5718bf6.png)

And if Privacy Possum and DuckDuckGo are not enough, AdGuard Tracking Protection Filter also has a Datadome entry ( https://filters.adtidy.org/extension/chromium/filters/3.txt )

![Captura de Pantalla 2020-06-29 a la(s) 18 58 07](https://user-images.githubusercontent.com/67610240/86060471-21bb9600-ba3b-11ea-8bf6-be1345a5d111.png)

**Comment by a-privacy-conscious-user** [comment]
Easyprivacy also has it in its list ( https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt )

![Captura de Pantalla 2020-06-29 a la(s) 19 42 03](https://user-images.githubusercontent.com/67610240/86063193-b83e8600-ba40-11ea-8a52-d235f9acf76a.png)
