### ISSUE TITLE
Feature request: Consider using DuckDuckGo tracker radar data

### ISSUE THREAD

**Issue by a-privacy-conscious-user** [disconnectme/disconnect-tracking-protection#199]
DuckDuckGo tracker radar

https://github.com/duckduckgo/tracker-radar

https://spreadprivacy.com/duckduckgo-tracker-radar/

is an automated tracker finder that provides data that can be incorporated into privacy blocklist like Disconnect. It currently feeds data to the newest Safari privacy report feature soon-to-be added to iOS 14 and macOS Big Sur https://twitter.com/DuckDuckGo/status/1275473734397317120

I noticed that disconnect lacks some trackers that are in DuckDuckGo data set ( I have reported some of them ). Also I am not sure if Disconnect has a way to automatically find new trackers at scale ( DuckDuckGo not only has search engine capabilities, it also has a nice pupeteer crawler to achieve this ). So I thought you should take a look a its data set to find domains you haven't added yet to your list ( now I know Disconnect is not an ad blocker but there are many fingerprinters that your list does not currently include that DDG does )

**Comment by a-privacy-conscious-user** [comment]
I also suggested it at AdGuard here https://github.com/AdguardTeam/AdguardFilters/issues/58396

**Comment by a-privacy-conscious-user** [comment]
Here is a list I made from domains not included in Disconnect but included on DuckDuckGo tracker radar data. They are a lot

On the followsing PDF you will find on the left, domains that are included on Disconnect but are not included on DuckDuckGo data sets; and on the right, you will find domains that are missed by Disconnect but not by DuckDuckGo

[text compare.pdf](https://github.com/disconnectme/disconnect-tracking-protection/files/4859043/text.compare.pdf)

**Comment by jawz101** [comment]
I'd also suggest Privacy Badger's preloaded list as they train Privacy Badger against the top N websites on the web each release.  Consequently you're getting the current landscape of the web today.

**Comment by llacb47** [comment]
that diff tool kinda sucks to be honest. also many domains included in duckduckgo tracker radar data are not trackers.  Discussion here: https://github.com/uBlockOrigin/uAssets/issues/7073

**Comment by a-privacy-conscious-user** [comment]
I would like to quote this reply because I think it adds to the discussion https://github.com/AdguardTeam/AdguardFilters/issues/58396#issuecomment-654655433
