### ISSUE TITLE
Consider adding wellsfargo tracker

### ISSUE THREAD

**Issue by ghost** [disconnectme/disconnect-tracking-protection#207]
This report has been updated, read the comment below

https://github.com/AdguardTeam/AdguardFilters/issues/58643

**Comment by a-privacy-conscious-user** [comment]
Given that the domains that I originally wanted to be blocked can't be blocked by Disconnect (first party domains) I modified the title and now I report this tracker ```https://rubicon.wellsfargo.com``` which is blocked by tools like adguard
