### ISSUE TITLE
Consider evaluating/adding some of these missing trackers

### ISSUE THREAD

**Issue by ghost** [disconnectme/disconnect-tracking-protection#219]
```
This list has been updated, read the comments below

az693360.vo.msecnd.net
vo.msecnd.net
track.securedvisit.com
s.yimg.jp

**Comment by a-privacy-conscious-user** [comment]
Some of these are websites. If we block them, there will be undesired breakage. But some are trackers. I changed the title of the issue to highlight that only some should be block. I apologized for the inconvenience. I will try to update the list to only reflect tracker with minimal user experience impact

**Comment by a-privacy-conscious-user** [comment]
I updated the list to only include tracker domains with minimal impact/breakage. You can check EasyPrivacy and you will find them there too
