### ISSUE TITLE
Consider analyzing some of these domains for tracking and including them on the list

### ISSUE THREAD

**Issue by ghost** [disconnectme/disconnect-tracking-protection#220]
According to DuckDuckGo (and also EasyPrivacy. Read the comments below), they exhibit tracking capabilities/activity

```
p.yotpo.com
distillery.wistia.com
pipedream.wistia.com
kampyle.com
log.olark.com
stats.olark.com

**Comment by a-privacy-conscious-user** [comment]
Some of these are websites. If we block them, there will be undesired breakage. But some are trackers. I changed the title of the issue to highlight that only some should be block. I apologized for the inconvenience. I will try to update the list to only reflect tracker with minimal user experience impact

**Comment by a-privacy-conscious-user** [comment]
I updated the list to only include tracker domains with minimal impact/breakage. You can check EasyPrivacy and you will find them there too
