### ISSUE TITLE
Difference between FingerprintingInvasive and FingerprintingGeneral

### ISSUE THREAD

**Issue by ghostwords** [disconnectme/disconnect-tracking-protection#227]
What makes something FingerprintingInvasive as opposed to FingerprintingGeneral? Apologies if this is already documented somewhere.

**Comment by disconnectme** [comment]
Policy and definitions are here. https://disconnect.me/trackerprotection#categories-of-trackers

We differentiate between two sub-categories of fingerprinters:
A tracker may be classified as a general fingerprinter if it uses browser or device features or properties in unintended ways to identify and track a particular user or device.
A tracker may be classified as an invasive fingerprinter if it uses an API to extract information about a particular user’s computing environment when the API was not designed to expose such information.

**Comment by ghostwords** [comment]
Got it, thank you! What's the rationale behind making this distinction?

**Comment by disconnectme** [comment]
https://blog.disconnect.me/our-new-approach-to-address-the-rise-of-fingerprinting/
