### ISSUE TITLE
API requests for vk.com (VKontakte)

### ISSUE THREAD

**Issue by NekR** [disconnectme/disconnect-tracking-protection#229]
Hello! I'm Arthur, I work for vk.com (VKontakte).

Right now, vk.com resides in Social category in this list. It makes sense, since vk.com is a social network.

Recently, vk.com started becoming a [Superapp](https://blog.gojekengineering.com/what-is-a-super-app-4f2d889451e6). This is means, vk.com is being in the center of a large ecosystem and many service work through it.

For example, every service in Mail.ru Group is migrating to an authentication through connect.vk.com. Authentication was an issue for us as well, since some browsers block requests to vk.com -- we couldn't use direct inclusion of our scripts on other domains to provide authentication.

Right now, we are facing another issue. Other services in our ecosystem needs to do requests to our API (api.vk.com). Those services live on other domains (e.g. something.com) and do not have their own API. It's solely based on connect.vk.com authentication and api.vk.com API.

This means such services would be blocked in cases when Disconnect list is used by the browsers and whole websites wouldn't work.

Is there a way to resolve this issue?

Thanks.

**Comment by Thisman** [comment]
Hi! Is anything updates in this issue? @disconnectme

**Comment by spirillen** [comment]
How about simply blacklist it and [Boy cut](https://mypdns.org/groups/my-privacy-dns/-/issues?scope=all&state=all&label_name[]=Boy_cut_Rusia) all of Russia until it extract there tropes from Ukraine? and support Democracy?

**Comment by ElForastero** [comment]
> How about simply blacklist it and [Boy cut](https://mypdns.org/groups/my-privacy-dns/-/issues?scope=all&state=all&label_name[]=Boy_cut_Rusia) all of Russia until it extract there tropes from Ukraine? and support Democracy?

Do you think Putin cares about social networks? I doubt it.

**Comment by Dr-Mx** [comment]
Having the same same blocking issue with maps.mail.ru and using their [Overpass API](https://wiki.openstreetmap.org/wiki/Overpass_API#Public_Overpass_API_instances).

**Comment by spirillen** [comment]
Now we know ho is pro Putin and against democracy, free will and elections.

![Pro Putin](https://user-images.githubusercontent.com/44526987/158679566-c8461309-5626-4351-8fe2-fec76277033d.jpg)
