### ISSUE TITLE
add Top500 / EU_US_most_common_trackers list

### ISSUE THREAD

**Issue by beerisgood** [disconnectme/disconnect-tracking-protection#232]
Please add this good list(s) from @Kees1958 for better tracking protection

> This blocklist is based on surveys of most used advertising and tracking technology (e.g. surveys of W3C, W3Tech and the on-line marketing community itself). These tech surveys are held once a year. This is the reason of the low update frequency (365 days and ad hoc corrections to correct website breakage). The surveys are oriented on Europe and North America, this is the reason this blocklist contains mostly EU and US based advertising and tracking networks.

https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist

**Comment by beerisgood** [comment]
@disconnectme

**Comment by Kees1958** [comment]
:-) is that your plan to get them into Edge blocklists which are sourced by Disconnect, smart move
