### ISSUE TITLE
 VGWort cookies should (likely) not be blocked as tracking cookie

### ISSUE THREAD

**Issue by scheinercc** [disconnectme/disconnect-tracking-protection#238]
Translated from a German

> Another example of tracking-free cookies are those of VG Wort, which are played out on many publishers' websites to enable the allocation of annual royalties to authors, but do not create cross-offer user profiles.

Source (German): https://www.heise.de/hintergrund/Cookies-Konsens-und-Co-Duerfen-wir-um-ihre-Zustimmung-bitten-4981016.html?wt_mc=rss.red.ho.ho.atom.beitrag.beitrag

Based on the quote above these cookies are not "following you from site to site to gather data about what you do online".

![image](https://user-images.githubusercontent.com/817856/101622972-dd153b80-3a6b-11eb-8b9b-e43150e2e9ed.png)

--
FYI, this is a port from https://bugzilla.mozilla.org/show_bug.cgi?id=1680912

**Comment by disconnectus** [comment]
We found no evidence on vgwort website committing not to track users as we define that term.
