### ISSUE TITLE
Combine Verizon Media Entities

### ISSUE THREAD

**Issue by Brandr0id** [disconnectme/disconnect-tracking-protection#240]
VMG has acquired a number of properties and a couple are currently represented as their own entities within the lists.

Based off of https://www.verizonmedia.com/our-brands it looks like **Adap.tv**,  **ADTECH**, **AOL** and **Yahoo!** can be combined into the Verizon Media grouping.

It also looks like the following domain could be added:
 - verizon.com

**Comment by Brandr0id** [comment]
@patjack PTAL

**Comment by hofbes-tozZu2-kyxzem** [comment]
https://github.com/disconnectme/disconnect-tracking-protection/issues/240#issuecomment-746940499

**Comment by hofbes-tozZu2-kyxzem** [comment]
https://github.com/disconnectme/disconnect-tracking-protection/issues/240#issuecomment-746940499

**Comment by hofbes-tozZu2-kyxzem** [comment]
verizon.com

**Comment by hofbes-tozZu2-kyxzem** [comment]
> @patjack PTAL
