### ISSUE TITLE
Fraud and Security product placed on block list

### ISSUE THREAD

**Issue by ashley-campbell-iovation** [disconnectme/disconnect-tracking-protection#255]
https://github.com/disconnectme/disconnect-tracking-protection/blob/2c2b6f7e1975f8107e8b999e1e4445122d27d7e8/services.json#L8156  

https://github.com/disconnectme/disconnect-tracking-protection/blob/2c2b6f7e1975f8107e8b999e1e4445122d27d7e8/entities.json#L6385  

iovation/iesnare is a product in the fraud and security space, it does not use tracking for the purpose of reselling or advertising. There is some confusion as to why this is on a blacklist when similar products are not on the list.

**Comment by disconnectus** [comment]
Policy analysis indicates this domain is properly classified as a tracker in our Content category and should remain on the list. From the privacy policy:
o        “When a Customer subscribes to our Services, they may place iovation cookies on your device or run our JavaScript code to enable the collection of certain device identifiers, and IP addresses. This information is no different to the types of information captured by common web analytics tools. The information is sent back to the Customer and subsequently passed onto Iovation for further processing.” https://www.transunion.com/privacy/iovation
