### ISSUE TITLE
Add mc.webvisor.org

### ISSUE THREAD

**Issue by mik0l** [disconnectme/disconnect-tracking-protection#258]
`https://mc.webvisor.org/metrika/watch.js`

Еxample: https://www.comss.ru

**Comment by gmvk** [comment]
https://github.com/disconnectme/disconnect-tracking-protection/commit/dd77e3cd44f93de32d33b1b451ac125881f90094#diff-24617f14de682a6440a50227fda13459dc434f61c0ba298896b23509aad013f8R12250

My Firefox in `about:url-classifier` does not find this domain.

**Comment by spirillen** [comment]
@gawk

It is there sometimes but mostly if you have a Russian IP https://mypdns.org/my-privacy-dns/matrix/-/issues/939238, The information is correct and verified.
