### ISSUE TITLE
Add Rambler Top100 Counter

### ISSUE THREAD

**Issue by mvk-foo** [disconnectme/disconnect-tracking-protection#262]
Rambler: `top100.ru`

Еxample: https://echo.msk.ru or https://lenta.ru

**Comment by unique30** [comment]
Unsubscribe 


Sent from Yahoo Mail for iPhone


On Tuesday, June 8, 2021, 8:47 AM, gmvk ***@***.***> wrote:




Rambler: top100.ru

Еxample: https://echo.msk.ru or https://lenta.ru
