### ISSUE TITLE
img.img-taboola.com is missing from Taboola domains

### ISSUE THREAD

**Issue by johannhof** [disconnectme/disconnect-tracking-protection#266]
It looks like Taboola is using img.img-taboola.com as a domain for hosting their tracking pixels. Taboola's official documentation makes no mention of that domain and the data that is included in the request but it's very likely used exclusively for tracking. There are other sources on the web that associate Taboola with this domain.

This was shared privately via screenshot and I don't have a site to reproduce on yet, I'll ask and add it later if possible.

Can you please verify and add it?

**Comment by spirillen** [comment]
<details><summary>note to self (@spirillen)</summary>

https://mypdns.org/my-privacy-dns/matrix/-/issues/1851

</details>

**Comment by disconnectus** [comment]
This subdomain does not appear to be in use. Domain is on our radar for future investigation.
