### ISSUE TITLE
AWS Cognito

### ISSUE THREAD

**Issue by siboulet** [disconnectme/disconnect-tracking-protection#28]
Getting `The resource at “https://cognito-idp.us-east-1.amazonaws.com/” was blocked because tracking protection is enabled.` using "Disconnect.me strict protection" on FF Nightly.

Please consider whitelisting AWS Cognito. Without this it's impossible to login to any site that uses AWS Cognito for authentication.

**Comment by carbureted** [comment]
Tracker protection's strict protection mode is highly likely to break sites (it blocks sites on the typical whitelist).
