### ISSUE TITLE
New domain for Vocento

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [disconnectme/disconnect-tracking-protection#287]
Vocento seems to be serving content on static.vocstatic.com.
This came to our attention while examining https://www.elcorreo.com/

**Comment by patjack** [comment]
Hi @bvandersloot-mozilla - thanks for flagging. We verified this new domain and will be adding shortly.

**Comment by bvandersloot-mozilla** [comment]
Thanks Patrick!
