### ISSUE TITLE
rlcdn.com belongs to LiveRamp, not TowerData

### ISSUE THREAD

**Issue by gunesacar** [disconnectme/disconnect-tracking-protection#288]
Hi,
I'd like to report an issue in the entity map. The `rlcdn.com` domain is owned by LiveRamp, not TowerData.
https://github.com/disconnectme/disconnect-tracking-protection/blob/fe83a8dce72167d185c8133db3a6c266b66f8fab/entities.json#L12267-L12270

Here is LiveRamp's documentation mentioning rlcdn.com:
https://docs.liveramp.com/connect/en/announcing-required-pixel-changes--7-2-19-.html
https://docs.liveramp.com/safe-haven/en/implementing-liveramp-s-cookie-sync-tag.html

Thank you.

**Comment by adamwelsh** [comment]
> Hi, I'd like to report an issue in the entity map. The `rlcdn.com` domain is owned by LiveRamp, not TowerData.
> 
> https://github.com/disconnectme/disconnect-tracking-protection/blob/fe83a8dce72167d185c8133db3a6c266b66f8fab/entities.json#L12267-L12270
> 
> Here is LiveRamp's documentation mentioning rlcdn.com: https://docs.liveramp.com/connect/en/announcing-required-pixel-changes--7-2-19-.html https://docs.liveramp.com/safe-haven/en/implementing-liveramp-s-cookie-sync-tag.html
> 
> Thank you.

The relationship with these companies is messy. 

https://www.atdata.com/blog/2011/07/11/new-liveramp-solution-featured-in-adexchanger
https://en.wikipedia.org/wiki/RapLeaf

Apparently Liveramp is a part of Rapleaf. Rapleaf was bought by Towerdata. Towerdata is now Atdata. These scummy tracking companies just keep getting bought and merged :)
