### ISSUE TITLE
Consider moving quantcast.com to the Content Category

### ISSUE THREAD

**Issue by artines1** [disconnectme/disconnect-tracking-protection#295]
There are some websites now relying on QuantCase's cookie consent management library to show the cookie banner. We have observed three breakages related to this([Bug 1776862](https://bugzilla.mozilla.org/show_bug.cgi?id=1776862),[Bug 1778434](https://bugzilla.mozilla.org/show_bug.cgi?id=1778434),[bug 1778491](https://bugzilla.mozilla.org/show_bug.cgi?id=1778491)). The cookie consent banner won't show correctly if Quantcast was blocked.

**Comment by disconnectus** [comment]
In addition to serving cookie consents, Quantcast meets our definition of tracking (see for example the passage from their privacy policy pasted below.) 

When making decisions on whether to move trackers to the Content category and as stated in our policy we "strive to find the balance between privacy, security, usability and promoting a better Internet for everyone." https://disconnect.me/trackerprotection#trackers-we-dont-block 

In this case, the unexpected breakage occurs only in Strict mode, which users manually turn on and are explicitly notified may cause some breakage. For this reason, our initial analysis is that Quantcast is properly classified at this time.

Thank you for bringing this issue to our attention and we are happy to dig in further if you would like to share additional information.

Quantcast privacy policy https://www.quantcast.com/privacy/ 
"When you visit a site or app operated by a Quantcast Partner, the Partner permits Quantcast to collect Log Data from their sites and apps through the use of Tags and Cookies; we also receive information directly from our Partners. We associate this information with a unique random identifier associated with your device (like a cookie ID) . . . When you visit a site or app that uses Quantcast Choice, we may use tags, cookies, SDKs, and plug-ins to store information about privacy notices that you have received and privacy choices that you have made."
