### ISSUE TITLE
Recategorize Mail.ru as Content

### ISSUE THREAD

**Issue by bvandersloot-mozilla** [disconnectme/disconnect-tracking-protection#306]
We've observed mail.ru being used to serve content as well[1]. Would it be more appropriately classified as Content?

1.  https://bugzilla.mozilla.org/show_bug.cgi?id=1799210

**Comment by patjack** [comment]
Hi @bvandersloot-mozilla, we did verify the breakage and after review, have decided to add `my.mail.ru` to the content section. Please let me know if you have any follow up questions. Thank you.
