### ISSUE TITLE
Requesting removal of usemessages.com from Analytics list

### ISSUE THREAD

**Issue by tuckertrainor** [disconnectme/disconnect-tracking-protection#313]
Hi! I'm late to follow up on the addition of `usemessages.com` in https://github.com/disconnectme/disconnect-tracking-protection/commit/662fb574d6f865be9c65d1655ddaf9a60d862631 in response to https://github.com/disconnectme/disconnect-tracking-protection/issues/299 but I'd like to request that it be removed. In the context of HubSpot's chat widget, the `js.usemessages.com` domain is solely used to import the widget's bootstrapping JS on the site that hosts the widget; no tracking calls are made from nor cookies stored on that domain. The net effect of blocking this domain would be removing the chat widget entirely from websites that include it on their pages. The existing analytics domains associated with HubSpot on this list would already apply to any analytic calls made by the widget.

Please let me know if I can provide additional details, clarification, or answer any questions in regard to this request. Thanks!

**Comment by disconnectus** [comment]
It appears this domain is used to serve JS and that JS initiates subsequent connections to tracking domains. We are closing out this issue but if you would like to continue the conversation please email support@disconnect.me. 

We base our decisions on publicly available information so it would be great if you could send specific citations from your privacy policy supporting your position that usemessages.com should not be classified as a tracker.
 
The most efficient way to be removed from the list is to make a legally binding commitment in your privacy policy, or other publicly available policy, like the following and resolve any inconsistencies it may have with existing policy language.
  
“Nothing in this policy contradicts the following statement: usemessages.com does not collect, retain or share any data regarding a particular user or device (including IP addresses and user identifiers) on sites or apps not owned by Hubspot.”
