### ISSUE TITLE
Consider adding threads.net to Facebook entity

### ISSUE THREAD

**Issue by Trikolon** [disconnectme/disconnect-tracking-protection#325]
The Facebook entity list here https://github.com/disconnectme/disconnect-tracking-protection/blob/137a71e5a33ea1a2a5c494c5ce0ec0fc92c507f9/entities.json#L5509C1-L5509C1 does not include threads.net yet. Please consider adding it.

**Comment by spirillen** [comment]
You need to list it as SpyWare as well... https://0xacab.org/my-privacy-dns/matrix/-/issues/640919
