### ISSUE TITLE
Adobe Embed blocked by Tracking Prevention

### ISSUE THREAD

**Issue by dpasut** [disconnectme/disconnect-tracking-protection#332]
### Domain(s) to review. Separate them by comma.

https://documentservices.adobe.com/

### Rationale for removing, adding, or recategorizing.

not a tracker, used to display PDFs using Adobe Embed API

### Where domain(s) observed. Separate them by comma.

all sites that use Adobe Embed 

### Additional notes

Here is a discussion of the issue: https://community.adobe.com/t5/acrobat-services-api-discussions/domexception-failed-to-read-the-sessionstorage-property-from-window-access-is-denied/td-p/13980467

All sites that use Adobe Embed API for pdf viewing are getting the error `Tracking Prevention blocked access to storage for https://documentservices.adobe.com/*`, with `*` being multiple paths, such as `/view-sdk/viewer.js`

These domains are necessary to display PDFs using this service. 

This is an issue mainly on Microsoft Edge, but is also an issue depending on selected security settings in Google Chrome.

**Comment by disconnectme** [comment]
Thanks for submitting this issue.

Adobe.com is not on our default blocklist, rather it is classified in our Content category (a tracker that we do not block by default). 

Partners who utilize our lists, like Microsoft Edge, may allow users to block domains in our Content category in other more aggressive privacy modes like an Incognito window or Strict mode. We are not in the best position to analyze or resolve this issue.
