### ISSUE TITLE
Domain Name False Positive

### ISSUE THREAD

**Issue by carlhancock** [disconnectme/disconnect-tracking-protection#333]
### Domain(s) to review. Separate them by comma.

gravity.com

### Rationale for removing, adding, or recategorizing.

We acquired the domain in 2022. We do not do ad or user tracking. Former owner was an ad tech company acquired by AOL and shut down. Domain continues to be included on tracking lists for this reason.

### Additional notes

The domain name gravity.com is currently listed in your tracking protection list. This is a false positive. We acquired the domain name gravity.com at the beginning of 2022 and are not in the business of ad, user, or any kind of tracking.

The former owner was indeed an ad tech company in the early to mid-2010s that was acquired by AOL and subsequently shut down. You will see the gravity.com domain name currently redirects to the primary website for our commercial OSS product. 

We have plans to migrate to this domain as our primary next year and I'm working on getting it removed from any tracking lists, etc. for that reason.

I see that it is associated with grvcdn.com which is another domain that the other business also used but we have no association with that domain and have no issue if it continues to be included in your tracking protection list.  But if you could kindly remove "gravity.com" from the list we'd appreciate it.

If you have any questions i'd be glad to answer them.  Thanks!

**Comment by disconnectme** [comment]
Hello,
 
Thank you for the information, we are evaluating your submission.
 
You can view our list changes here:
https://github.com/disconnectme/disconnect-tracking-protection 

Disconnect Support

**Comment by carlhancock** [comment]
Thank you for the quick turnaround!
