### ISSUE TITLE
Blocking geetest.com as FingerprintingInvasive breaks CAPTCHA or Log in in certain websites.

### ISSUE THREAD

**Issue by artines1** [disconnectme/disconnect-tracking-protection#334]
Blocking geetest.com as a fingerprinter causes different site breakages in Firefox. 

Here are the bug reports.

[Bug 1857891 - Captcha not showing when trying to login on act.hoyolab.com with Standard ETP](https://bugzilla.mozilla.org/show_bug.cgi?id=1857891)
[Bug 1858122 - ETP Fingerprinters Blocking blocks api.geetest.com and static.geetest.com causing captcha in passport.bilibili.com couldn't load](https://bugzilla.mozilla.org/show_bug.cgi?id=1858122)
[Bug 1858428 - Login form does not load on missevan.com with Standard ETP](https://bugzilla.mozilla.org/show_bug.cgi?id=1858428)
[Bug 1858669 - Captcha does not load when trying to login on bilibili.com with Standard ETP](https://bugzilla.mozilla.org/show_bug.cgi?id=1858669)
[Bug 1858884 - The page does not load content at hoyolabpp.com with ETP set to STANDARD](https://bugzilla.mozilla.org/show_bug.cgi?id=1858884)
[Bug 1859263 - The login button does not respond at jiayuan.com with ETP set to STANDARD](https://bugzilla.mozilla.org/show_bug.cgi?id=1859263)

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review. Please note that the GeeTest domain is in our Anti-Fraud category. https://disconnect.me/trackerprotection#categories_of_trackers

**Comment by disconnectme** [comment]
Verified this domain is actively fingerprinting. Will remain on Invasive Fingerprinting and in the Anti-fraud categories for now. Will monitor for breakage and additional bug reports.
