### ISSUE TITLE
Remove orkut.com from list of Google domains

### ISSUE THREAD

**Issue by aakallam** [disconnectme/disconnect-tracking-protection#336]
### Domain(s) to review. Separate them by comma.

orkut.com

### Rationale for removing, adding, or recategorizing.

This domain has not been owned by Google since 2016

**Comment by patjack** [comment]
Thanks for bringing this to our attention. We reviewed and removed the domain from Google entity and from our list altogether.

**Comment by aakallam** [comment]
Thanks, Patrick!
