### ISSUE TITLE
Consider adding to the blocklist

### ISSUE THREAD

**Issue by mik0l** [disconnectme/disconnect-tracking-protection#337]
### Domain(s) to review. Separate them by comma.

bitrix.info, informer.yandex.ru

### Rationale for removing, adding, or recategorizing.

adding

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.

**Comment by changoju** [comment]
> ### Domain(s) to review. Separate them by comma.
> 
> bitrix.info, informer.yandex.ru
> ### Rationale for removing, adding, or recategorizing.
> 
> adding
> ### Where domain(s) observed. Separate them by comma.
> 
> _No response_
> ### Additional notes
> 
> _No response_
