### ISSUE TITLE
Please add api.adinplay.com and elb.the-ozone-project.com

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#338]
### Domain(s) to review. Separate them by comma.

api.adinplay.com, elb.the-ozone-project.com

### Rationale for removing, adding, or recategorizing.

These domains initiate connections with multiple other tracking domains.

### Where domain(s) observed. Separate them by comma.

hole-io.com

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.

**Comment by Kclynn77** [comment]
I absolutely do not know how to do all this. I'm in process of taking classes to learn all this language. I don't know what I've done wrong here. How to correct it but I am learning and I'm getting myself educated. So I don't make these mistakes again or whatever mistakes i'm making
