### ISSUE TITLE
Please add location trackers

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#340]
### Domain(s) to review. Separate them by comma.

geolocation.onetrust.com, location.p7cloud.net

### Rationale for removing, adding, or recategorizing.

Tracks user's location

### Where domain(s) observed. Separate them by comma.

slate.com, ostsee-zeitung.de

### Additional notes

https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location

https://location.p7cloud.net/locdot

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
