### ISSUE TITLE
Remove NoFraud domains from the blocklist

### ISSUE THREAD

**Issue by vladnofraud** [disconnectme/disconnect-tracking-protection#341]
### Domain(s) to review. Separate them by comma.

nofraud.com, services.nofraud.com, cdn-checkout.nofraud.com, dynamic-api-checkout.nofraud.com

### Rationale for removing, adding, or recategorizing.

This blocks our fraud detection and checkout services for our merchants

### Where domain(s) observed. Separate them by comma.

https://nofraud-prod.mybigcommerce.com

### Additional notes

Hello

I am reaching out on behalf of NoFraud, which specializes in providing anti-fraud and fraud prevention services to our merchants through our order analysis service and our checkout product.

The heart of our service lies in the thorough examination of user data throughout the order and purchase processes, ensuring that our merchants exclusively receive legitimate orders. Moreover, our system adeptly identifies and flags users deemed potential fraudsters, consequently preventing the processing of suspicious orders and safeguarding our merchants from revenue loss due to fraudulent activities.

We have encountered a challenge from stemming the inclusion of our domains in a blocklist. This predicament extends beyond the acceptable blocking of fingerprint APIs integral to our services. It is impeding our ability to verify legitimate orders, preventing our checkout from launching and consequently placing our merchants at risk of receiving fraudulent orders.

To address this issue effectively, we kindly request a comprehensive review and removal of the following domains from the blocklist:

- nofraud.com
- cdn-checkout.nofraud.com
- dynamic-api-checkout.nofraud.com

We understand the importance of blocking specific fingerprinting APIs, and we are in agreement with such measures. However, we emphasize the criticality of unblocking the aforementioned domains to restore the proper functioning of our order verification processes.

Should there be a need to restrict fingerprinting APIs, we propose the specific blocking of the domain: https://services.nofraud.com/. We are actively addressing the concern related to services.nofraud.com and will promptly inform you once the issue has been successfully resolved. 

Your prompt attention to this matter is greatly appreciated, as it directly impacts the ability of our merchants to conduct secure and efficient transactions.

Thank you for your understanding and cooperation.

Vladimir Stupavsky
Director of Software Development @ NoFraud
v.stupavsky@nofraud.com

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
