### ISSUE TITLE
`app.datadoghq.eu` fails to load due to `datadoghq.com` rule

### ISSUE THREAD

**Issue by jakub-g** [disconnectme/disconnect-tracking-protection#345]
### Domain(s) to review. Separate them by comma.

datadoghq.com

### Rationale for removing, adding, or recategorizing.

Datadog EU app fails to load

### Where domain(s) observed. Separate them by comma.

app.datadoghq.eu

### Additional notes

See details in ~https://github.com/webcompat/web-bugs/issues/132384~

- Linked [bugzilla ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1875060) as the above webcompat ticket was closed.

Blocklisting datadoghq.com [here](https://github.com/disconnectme/disconnect-tracking-protection/commit/03fb2fd45f13e3732f7962285b47efea6046f9e4#diff-24617f14de682a6440a50227fda13459dc434f61c0ba298896b23509aad013f8R4047) prevents loading the https://app.datadoghq.eu webapp (which uses `static.datadoghq.com` subresources) in Firefox with strict blocking.

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.

**Comment by jakub-g** [comment]
@patjack thanks for having a look on this. Do you know what is the expected timeline for the update to reach Firefox users? Thanks in advance.
