### ISSUE TITLE
Consider reclassifying inmobi.com from tracker to content tracker

### ISSUE THREAD

**Issue by mb** [disconnectme/disconnect-tracking-protection#348]
### Domain(s) to review. Separate them by comma.

inmobi.com

### Rationale for removing, adding, or recategorizing.

It serves cookie banners, blocking them breaks websites

### Where domain(s) observed. Separate them by comma.

https://www.mirror.co.uk/news/uk-news/poorly-penguin-scots-zoo-rushed-32680501.amp

### Additional notes

See https://bugzilla.mozilla.org/show_bug.cgi?id=1893987

**Comment by disconnectme** [comment]
Thank you for bringing this to our attention. Our technical and policy review determined that inmobi.com meets our definition of tracking based on technical observations (e.g., Request URL cmp.inmobi.com is present on many 3P domains) and several portions of the InMobi policy, including but not limited to the following:
 
“When you view an advertisement distributed through InMobi on a site, app or other digital media, we may collect information on your device and your interaction with the advertisement. This information enables us to serve advertisements to you, improve our Services including to recognize your device when you use other sites and applications that have partnered with us.”

“Network information, including:
• Mobile carrier
• Network provider or ISP
• Network type (e.g., WiFi or cellular)
• IP address
• IDs of WiFi access points to which your device is connected
• Date and time of connection”
 
“Device identifiers. Device identifiers are alphanumeric strings that are unique to your device. These include:
• iOS devices’ Identifier for Advertising (IDFA) and iOS Identifier for Vendors (IDFV)
• Google Advertising ID (GAID), or Android ID for Android devices
• Identifier for Advertising on OTT and CTV platforms
• International mobile equipment identity (IMEI), in certain jurisdiction as permitted by applicable law
• Cookie IDs”
 
“We use the information that we collect about your device to:
• Display advertisements on your device, which may include interest-based advertising customized to your interests, preferences, locations
• For remarketing or retargeting i.e. to display relevant ads if you have previously visited/accessed/downloaded a site or mobile application that we partner with
• For bidding to serve advertisements and to determine which ads are most effective
• Analyze and provide our demand partners or advertisers reports on the effectiveness of advertisements and campaigns, including across different types of devices based on our determination of devices that are related to the same person. We, or third parties whom we engage to provide this service, may use cross-device data to provide interest-based advertising services and to deliver tailored ads to users across multiple mobile devices including over the top applications and smart televisions
• Avoid showing you the same ads too many times
• Build custom audience segments to enable our customers and partners better target their advertisements and offers”
 
“InMobi may share the information we collect or receive about you as described in this Policy as follows:
• Publishers and Supply Partners. We may share your information with publishers (the app or site publishers) to help them understand how users interact with their apps and sites and advertisements on their apps and sites
• Demand Partners and Advertisers. We may share your information with demand partners, brands and advertisers who use our Marketing Platform, to allow them to understand the performance of their campaigns; and to help them better target their campaigns, products or offerings
• Marketing Partners. We may share your information with data partners who help us with better understanding your preferences by providing data enrichment, analytics and identification services and measurement companies who help us with attribution and tracking of advertisements distributed through us (“Marketing Partners”)”

In regard to the specific issue of cookie banners breaking, we were unable to reproduce the issue in the video on Bugzilla. We tried to recreate the observed breakage in Firefox on Android, iOS, and Mac devices, including on both US and UK connections/IPs, with and without tracker protection. Additionally, we tested on iOS/Mac using Safari and Chrome on Mac and did not observe any discrepancy in page load or rendering.

The Content category of our list strives to balance usability and privacy harm. Although we understand InMobi is offering a service, our review has determined that InMobi also is collecting and retaining data about particular devices/users on websites that InMobi does not own, and this activity fits our definition of tracking: https://disconnect.me/trackerprotection. 

Based on this analysis we believe this domain is properly classified but please feel free to provide additional information and we’ll be sure to consider.
