### ISSUE TITLE
x.com is missing from twitter's property

### ISSUE THREAD

**Issue by artines1** [disconnectme/disconnect-tracking-protection#350]
### Domain(s) to review. Separate them by comma.

x.com

### Rationale for removing, adding, or recategorizing.

The twitter.com is offically replaced by x.com. This cause some problem on Firefox because of blocking twitter resource domains under x.com.

### Additional notes

Mozilla has a hotfix for this issue: https://github.com/mozilla-services/shavar-prod-lists/commit/e597c073b04c0543d8fe745efe6e78b60f02ac4f

**Comment by mozfreddyb** [comment]
From our observation, the twitter.com to x.com migration breaks the web page for all users of the Disconnect list that block social trackers.

Our hotfix will resolve the issue for Firefox users in due time, but from our cursory testing, this also affects users of the disconnect extension on Firefox and Chrome.

**Comment by disconnectme** [comment]
Thanks for flagging this. We will push this fix shortly.
