### ISSUE TITLE
Regarding a.js entries

### ISSUE THREAD

**Issue by spirillen** [disconnectme/disconnect-tracking-protection#356]
Both `flightzy.date.` and `zymerget.bid` appears to be inactive, `zymerget.bid` is no longer registered and `flightzy.date.` seems to just be parked, I know this doesn't mean it can be active from sunpath.

```bash
Drilling for flightzy.date

flightzy.date.  3600    IN      NS      ns2.parktons.com.
flightzy.date.  3600    IN      NS      ns.parktons.com.
flightzy.date.  3600    IN      A       46.8.8.100
```

`parktons.com` are a well know domain pirate https://github.com/mypdns/matrix/commit/dfbf28a43d34d05b7ed14b0e9c4511d18ece3822

https://github.com/disconnectme/disconnect-tracking-protection/blob/e9828f6fffab714ce502b55ebeae8145bce320fd/entities.json#L1976

**Comment by disconnectme** [comment]
Thanks for the submission, this issue is under review.
