### ISSUE TITLE
`banner-rotation.com` seems to be a outdated asset for Awin

### ISSUE THREAD

**Issue by spirillen** [disconnectme/disconnect-tracking-protection#357]
`banner-rotation.com` seems to be a outdated asset for Awin

```bash
Drilling for banner-rotation.com

banner-rotation.com.    172800  IN      NS      ns.parktons.com.
banner-rotation.com.    172800  IN      NS      ns2.parktons.com.
banner-rotation.com.    3600    IN      A       46.8.8.100
```

https://github.com/disconnectme/disconnect-tracking-protection/blob/e9828f6fffab714ce502b55ebeae8145bce320fd/entities.json#L2634C10-L2634C29

--------

`parktons.com` are a well know domain pirate https://github.com/mypdns/matrix/commit/dfbf28a43d34d05b7ed14b0e9c4511d18ece3822

**Comment by disconnectme** [comment]
Thanks for the submission, this issue is under review.
