### ISSUE TITLE
Remove wistia from trackers list

### ISSUE THREAD

**Issue by prabushitha** [disconnectme/disconnect-tracking-protection#360]
### Domain(s) to review. Separate them by comma.

wistia.com

### Rationale for removing, adding, or recategorizing.

Block only the applicable subdomains without blocking the entire list of subdomains breaks product features

### Where domain(s) observed. Separate them by comma.

fast.wistia.com,embed-cloudfront.wistia.com

### Additional notes

Wistia is a service which provides video embed service to other businesses.
fast.wistia.com & embed-cloudfront.wistia.com is being used while embedding videos and seems it's being blocked. Below should be removed from trackers.
- embed-cloudfront.wistia.com
- fast.wistia.com
Since entire wistia.com is marked as trackers, it seems it's blocking the above 2 subdomains. (**Note that I'm not an employee** from wistia. we're using wistia to embed videos to our website and firefox is blocking the video loading)

Here's the firefox error (firefox relies on disconnect me list of trackers to block these websites)

The resource at “https://fast.wistia.com/assets/external/E-v1.js” was blocked because content blocking is enabled.

**Comment by disconnectme** [comment]
Thanks for the submission, this issue is under review.
