### ISSUE TITLE
Remove our domains from the trackers list to avoid disrupting the search functionality.

### ISSUE THREAD

**Issue by Mblanchetdeverly** [disconnectme/disconnect-tracking-protection#361]
### Domain(s) to review. Separate them by comma.

platform.cloud.coveo.com ; platform-eu.cloud.coveo.com ; org.coveo.com ; static.cloud.coveo.com

### Rationale for removing, adding, or recategorizing.

Breakage of sites’ search functionality

### Additional notes

We are reaching out because after  reviewing the effects of [this PR ](https://github.com/disconnectme/disconnect-tracking-protection/commit/25d7af6aa3f6c530b53800f706952a920e76a623)on our platform,  we believe that some of our domains have been incorrectly categorized and should be removed from your blocking lists. We have evidence from our customers showing that, as of today, this categorization is disrupting legitimate search activities and user experience, as their end-users cannot receive search results due to the blocking. Specifically:

- Both platform.cloud.coveo.com and platform-eu.cloud.coveo.com are classified as tracking, even though they host our core search apis and are solely used for search purposes. The original issue [here](https://github.com/disconnectme/disconnect-tracking-protection/issues/358#issue-2347300911) did not include them, and neither did the [change to mypdns](https://github.com/mypdns/matrix/commit/da771ed9400144b922d7264bab3af4dfeba964fc). Inclusion of platform.cloud.coveo.com and platform-eu.cloud.coveo.com in your current tracker list is currently impacting our customers’ activities, breaking multiple sites, including e-commerce sites. The net effect is breakage of the sites’ search functionality on the front page.

- static.cloud.coveo.com is our CDN (and is indeed included in the content section). *.org.coveo.com hosts our core apis and is the non-tracking counterpart to our analytics  apis. This should not be included as content urls.

- The Coveo entry is classified as ‘Advertising’. A more appropriate category may be ‘Analytics’, as, as previously mentioned, Coveo does not provide advertising services nor perform cross-tracking activities.

Thank you for your prompt attention to this matter.

**Comment by disconnectme** [comment]
Thanks for the submission, this issue is under review.

**Comment by Mblanchetdeverly** [comment]
@disconnectme do you have an update on your review? We are happy to provide you with more information, if necessary. Thanks!

**Comment by disconnectme** [comment]
Thank you for bringing this to our attention. Please see our reply to the initial Coveo issue as it provides a detailed breakdown of why the [coveo.com](http://coveo.com/) subdomains meet our definition of Tracking: https://github.com/disconnectme/disconnect-tracking-protection/issues/358#issuecomment-2176938718 

Please provide citations to publicly available technical and policy information that make clear that the subdomains you mentioned do NOT meet our definition of tracking. For example, a legally binding public statement, like we provided to Coveo here https://github.com/disconnectme/disconnect-tracking-protection/issues/358#issuecomment-2164163312, in your privacy policy stating something substantively similar to the following: 

"Nothing in this policy contradicts the following statement: Except for subdomains [LIST OF ALL TRACKING SUBDOMAINS], Coveo’s domain coveo.com does not collect, retain or share any data regarding a particular user or device (including IP addresses and user identifiers) on sites or apps not owned by Coveo.”

If such a statement is made, any inconsistencies it may have with existing policy or marketing language must be resolved. 

Regarding any breakage, please provide detailed steps for reproducing the breakage so we can evaluate it.
