### ISSUE TITLE
sardine.ai tracking and fingerprinting

### ISSUE THREAD

**Issue by somehundred** [disconnectme/disconnect-tracking-protection#362]
### Domain(s) to review. Separate them by comma.

sardine.ai

### Rationale for removing, adding, or recategorizing.

tracking and fingerprinting

### Where domain(s) observed. Separate them by comma.

stockx.com, candy.com

### Additional notes

Tracks and fingerprints users. Here are some quotes from their webpage:

> Device and Behavior
> Capture deep device intelligence and behavior biometrics for every customer touchpoint and interaction on your website or app.

> All the signals you need to detect fraud
> We monitor every customer interaction for smart signals that may indicate fraud. Then we combine that with data from 35+ providers to give you the most precise risk score.

> Behavior Biometrics
> Typing speed, mouse movement, scrolling and swiping patterns, hesitation and distraction events, stressed behavior, and context switching.
> 
> Device Intelligence
> Device and browser fingerprints, True IP and location, emulators, tampered apps, remote access tools (RATs), Proxy piercing, VPN detection, bots, and device farms.
> 
> Identity Signals
> Social Security Number (SSN), phone carrier, name matching, line tenure, port status events, domain reputation, email lifespan, IP address associations, and social profile.
> 
> Transaction Data
> Bank identity and transaction history, counterparty risk, merchant identity, partial card number to name matching, BIN lists, Early Warning Systems, and SardineX consortium.

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review.

**Comment by disconnectme** [comment]
Closing for now, will update thread if action taken.
