### ISSUE TITLE
nocodelytics.com tracking

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#363]
### Domain(s) to review. Separate them by comma.

nocodelytics.com

### Rationale for removing, adding, or recategorizing.

tracking

### Where domain(s) observed. Separate them by comma.

tubemagic.com

### Additional notes

Quotes from their website:

> The simplest and easiest way to track clicks, searches, CMS items and more on your Webflow site.

> Track buttons and links in just a few clicks
> 
> Analytics doesn't have to be frustrating or overwhelming.
> 
> Nocodelytics makes it easy to know how many times a user has clicked a button or a link. 

> See what users search for
> 
> Want to write content that people are interested? Or build features that people want?
> 
> With Nocodelytics, you can see what searches are being made on your Webflow site.

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review.

**Comment by disconnectme** [comment]
Closing for now, will update thread if action taken.
