### ISSUE TITLE
Connection initiators with tracking domains: papayads.net, adxbid.info

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#364]
### Domain(s) to review. Separate them by comma.

papayads.net, adxbid.info

### Rationale for removing, adding, or recategorizing.

initiating connections with tracking domains

### Where domain(s) observed. Separate them by comma.

randomwordgenerator.com

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.
