### ISSUE TITLE
Connection initiator with tracking domains: player.anyclip.com

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#365]
### Domain(s) to review. Separate them by comma.

player.anyclip.com

### Rationale for removing, adding, or recategorizing.

initiating connections with many tracking domains

### Where domain(s) observed. Separate them by comma.

www.thesaurus.com

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.
