### ISSUE TITLE
Connection initiators with tracking domains: netpub.media, vlitag.com

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#367]
### Domain(s) to review. Separate them by comma.

netpub.media, vlitag.com

### Rationale for removing, adding, or recategorizing.

initiating connections with advertising / tracking domains

### Where domain(s) observed. Separate them by comma.

travelkuku.com, themezon.net

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.
