### ISSUE TITLE
b3mxnuvcer.com analytics

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#368]
### Domain(s) to review. Separate them by comma.

asset.b3mxnuvcer.com

### Rationale for removing, adding, or recategorizing.

collecting information about users device

### Where domain(s) observed. Separate them by comma.

https://www.revenuehero.io/

### Additional notes

Repeatedly requests api.b3mxnuvcer.com/sdk/event/update_properties initiated by asset.b3mxnuvcer.com/b3mxnuvcer.js.

Payload is encoded. After decoding it using ChatGPT (it was mentioning Caesar cipher), the following phrases appear in payload:

User ID
Event Name: revenuhero
Event Properties
Page Title: RevenuHero 1 Mrfound lead conversion * scheduling
Reference Domain, URL, Page Value URL
Page Load Time
Platform, Screen Width, Screen Height
Auto: true

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.
