### ISSUE TITLE
Some misclassification of Coveo's domains

### ISSUE THREAD

**Issue by jebeaudet** [disconnectme/disconnect-tracking-protection#369]
### Domain(s) to review. Separate them by comma.

platform.cloud.coveo.com,platform-eu.cloud.coveo.com

### Rationale for removing, adding, or recategorizing.

Breaking core functionality

### Where domain(s) observed. Separate them by comma.

support.goto.com,wktaaeu.my.site.com

### Additional notes

Hi

Following #361, I'd like to provide here 2 examples of sites having their functionality broken by blocking the domains platform.cloud.coveo.com and platform-eu.cloud.coveo.com.

platform.cloud.coveo.com -> https://support.goto.com/search#q=test&t=allTab
platform-eu.cloud.coveo.com -> https://wktaaeu.my.site.com/nlcommunity/s/global-search/%40uri?language=en_US#q=test&sort=relevancy

Thank you for your understanding!

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.

**Comment by jebeaudet** [comment]
Hi @disconnectme,
I’m following up on this ticket to check if there has been any decision on the presented issue, considering the samples of site breakage noted above. A substantial part of our customers are still suffering from non-functional websites with tracker protection enabled.
Thank you!
