### ISSUE TITLE
Remove CDN Edg.io and affiliated domains

### ISSUE THREAD

**Issue by slangley-edgio** [disconnectme/disconnect-tracking-protection#371]
### Domain(s) to review. Separate them by comma.

edg.io, limelight.com, clickability.com, llnwd.net, uplynk.com

### Rationale for removing, adding, or recategorizing.

CDN Provider, current blocking is breaking customer content and workflows

### Where domain(s) observed. Separate them by comma.

llnwd.net

### Additional notes

Customers using the Edg.io CDN are seeing issues where tracking protections must be disabled to use content from the CDN, for example, video content hosted on llnwd.net. This issue has been observed by multiple end users on Firefox as well as other browsers using the Disconnect blacklists which are imported. We are requesting removal from the blacklist as this breaks functionality for a large number of users given the size and usage of our network.

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.

**Comment by slangley-edgio** [comment]
Clarification requested; this is marked closed as completed, but were any changes made?

**Comment by spirillen** [comment]
Try reading the full message...

> **Closing for now, will update thread if action taken.**

**Comment by slangley-edgio** [comment]
Apologies since this 

> Try reading the full message...
> 
> > **Closing for now, will update thread if action taken.**

Apologies, trying to determine the workflow here. I would expect an issue under review to still be in an Open state, given this is customer affecting, as well as it appears these updates take a while to get into the pipeline. I will continue to monitor the issue, thank you.

**Comment by spirillen** [comment]
Without knowing it for sure, I do believe they have chosen to reverse the usual workflow, do to the number of false FP's which would make seance to all blacklist maintainers.

**Comment by disconnectme** [comment]
To help aid in the review, please note the following guidelines:

- We only consider publicly available information in determining domain categorization.
- Evidence supporting your position should be in the form of specific citations to publicly available information. 
- Appeals must explain in detail how the evidence shows that the domain in question does not meet our definition of Tracking and/or Tracker Categories found here: https://disconnect.me/trackerprotection.
- Breakage examples should be in the form of specific example sites where the breakage can be observed with clear, repeatable steps to recreate the breakage.
