### ISSUE TITLE
Blocking platform.cloud.coveo.com breaks www.lcbo.com

### ISSUE THREAD

**Issue by jrmuizel** [disconnectme/disconnect-tracking-protection#372]
### Domain(s) to review. Separate them by comma.

platform.cloud.coveo.com

### Rationale for removing, adding, or recategorizing.

It breaks useful content

### Where domain(s) observed. Separate them by comma.

www.lcbo.com

### Additional notes

Product images don't load on https://www.lcbo.com/en/new-arrivals/wines#t=clp-new_arrivals-wines&sort=relevancy&layout=card in Firefox with Private Browsing/ETP

See https://bugzilla.mozilla.org/show_bug.cgi?id=1923721

**Comment by jebeaudet** [comment]
I'll take the liberty to link https://github.com/disconnectme/disconnect-tracking-protection/issues/369 for more breakage example.

**Comment by spirillen** [comment]
The decision have already been published here https://github.com/disconnectme/disconnect-tracking-protection/issues/358

I do not see the needs to keep asking this project to brake its principles, because some webdesign don't know how to develop a website.

**Comment by disconnectme** [comment]
Thank you for the submission, this issue is under review. Closing for now, will update thread if action taken.
