### ISSUE TITLE
Blocking cookielaw.org & onetrust.com domains breaks privacy rights functionality

### ISSUE THREAD

**Issue by boyadamsam** [disconnectme/disconnect-tracking-protection#373]
### Domain(s) to review. Separate them by comma.

cookielaw.org, onetrust.com, onetrust.io

### Rationale for removing, adding, or recategorizing.

Recategorize: Blocking breaks privacy rights functionality on websites

### Where domain(s) observed. Separate them by comma.

cbs.com, cbsnews.com, cbssports.com, paramountplus.com, pluto.tv

### Additional notes

We use a privacy technology vendor named Onetrust to power much of our privacy infrastructure.

Several of our websites reported users are encountering site functionality problems when trying to exercise their privacy rights, such as opting out of sharing data and targeted advertising. My team investigated and was able to reproduce the reported bug.

We discovered the cause of the bug is that users with ad blocker extensions or on a browser such as Firefox are by default blocking two domains from our privacy vendor OneTrust which are critical to the functioning of our CMP (Consent Management Platform):
- cookielaw.org
- onetrust.com
- onetrust.io

These three domains are used solely for the essential services needed to run our privacy software. They're not used for marketing, sales, or advertising. Blocking them not only causes site functionality issues it keeps our users from being able to exercise their privacy rights.

<img width="856" alt="cookielaw-domain" src="https://github.com/user-attachments/assets/7729886c-71ee-4664-a438-715a24dac6bb">

<img width="901" alt="onetrust-domain" src="https://github.com/user-attachments/assets/cd855db7-341f-4816-812c-f816cfc880b5">

**Comment by disconnectme** [comment]
Thank you for your submission. Our technical and policy review previously determined that the [onetrust.com](http://onetrust.com/) and [onetrust.io](http://onetrust.io/) domains meet our definition of Tracking (see https://disconnect.me/trackerprotection), and that these domains are properly classified.
