### ISSUE TITLE
system-notify.app abusive notifications

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#374]
### Domain(s) to review. Separate them by comma.

system-notify.app

### Rationale for removing, adding, or recategorizing.

Pop-up ads as notifications

### Where domain(s) observed. Separate them by comma.

clk.kim

### Additional notes

`system-notify.app` is loaded in `clk.kim` and asks for notifications. If notifications are enabled then this domain sends abusive pop-up ad notifications.

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
