### ISSUE TITLE
Connection initiator with tracking domains: hbagency.it 

### ISSUE THREAD

**Issue by andris86** [disconnectme/disconnect-tracking-protection#375]
### Domain(s) to review. Separate them by comma.

hbagency.it

### Rationale for removing, adding, or recategorizing.

Initiating connections with tracking domains

### Where domain(s) observed. Separate them by comma.

oii.io

### Additional notes

Load website `oii.io` wait around 20 seconds and https://hbagency.it/cdn/prebid_8_40_ng.js will start initiating hundreds of connections with many ad and tracking domains. All of them are blocked except `ad.360yield-basic.com`.

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
