### ISSUE TITLE
Didomi needs a recategorization to Consent Management

### ISSUE THREAD

**Issue by pggpgg** [disconnectme/disconnect-tracking-protection#376]
### Domain(s) to review. Separate them by comma.

https://cmppartnerprogram.withgoogle.com/

### Rationale for removing, adding, or recategorizing.

Didomi is a consent management platform, not an advertiser. They are comparable to OneTrust or Osano

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.

**Comment by pggpgg** [comment]
Sorry for the poor formatting in my initial inquiry.

The domain to review is privacy-center.org - attributed to Didomi and classified under "Advertising"

The link I provided meant to show they're part of the Google CMP Partners program.

You can find Didomi on www.simons.ca , for example
