### ISSUE TITLE
Falsely prohibited - code.bdstatic.com

### ISSUE THREAD

**Issue by AnnAngela** [disconnectme/disconnect-tracking-protection#378]
### Domain(s) to review (separate domains by comma).

code.bdstatic.com

### Rationale for removing, adding, or recategorizing (please provide citations to publicly available information).

This site is used to provide code CDN, not tracking people.

### Where domain(s) observed (separate domains by comma).

ffcafe.cn

### Please include example website(s) where the breakage can be observed with clear, repeatable steps to recreate the breakage (separate domains by comma).

[https://www.ffcafe.cn/join-us/](https://www.ffcafe.cn/join-us/)

### Additional notes

In [https://www.ffcafe.cn/join-us/](https://www.ffcafe.cn/join-us/), major scripts are loaded from code.bdstatic.com, and the page is broken:

![image](https://github.com/user-attachments/assets/8df45924-1adf-4f9c-bb83-556727ba6e1e)

In <https://github.com/disconnectme/disconnect-tracking-protection/blob/fec791f0ae656ad6b08bc7eb2d1f1c5c4cab6689/services.json#L12248>, the whole `bdstatic.com` is forbidden, but I think the `code.bdstatic.com` should be an exception.

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
