### ISSUE TITLE
Blocking CDN static.ctctcdn.com breaks event registration

### ISSUE THREAD

**Issue by zrhoffman** [disconnectme/disconnect-tracking-protection#379]
### Domain(s) to review (separate domains by comma).

static.ctctcdn.com

### Rationale for removing, adding, or recategorizing (please provide citations to publicly available information).

Needed in order for users to register for events.

### Where domain(s) observed (separate domains by comma).

lp.constantcontactpages.com

### Please include example website(s) where the breakage can be observed with clear, repeatable steps to recreate the breakage (separate domains by comma).

https://lp.constantcontactpages.com/ev/reg/gt3kxzy

### Additional notes

See: https://github.com/webcompat/web-bugs/issues/143806 and https://bugzilla.mozilla.org/show_bug.cgi?id=1930620

Steps for https://lp.constantcontactpages.com/ev/reg/gt3kxzy :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/gt3kxzy
3. If necessary, click CloudFlare checkbox

Steps for https://lp.constantcontactpages.com/ev/reg/n9pn78r :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/n9pn78r
3. If necessary, click CloudFlare checkbox

Steps for https://lp.constantcontactpages.com/ev/reg/dsbtxds :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/dsbtxds
3. If necessary, click CloudFlare checkbox

Steps for https://lp.constantcontactpages.com/ev/reg/fmazxup :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/fmazxup
3. If necessary, click CloudFlare checkbox

Steps for https://lp.constantcontactpages.com/ev/reg/7xtwh2t :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/7xtwh2t
3. If necessary, click CloudFlare checkbox

Steps for https://lp.constantcontactpages.com/ev/reg/fyvnxgf :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/fyvnxgf
3. If necessary, click CloudFlare checkbox

Steps for https://lp.constantcontactpages.com/ev/reg/4jx3sn5 :
1. Start Firefox private browsing session
2. Go to https://lp.constantcontactpages.com/ev/reg/4jx3sn5
3. If necessary, click CloudFlare checkbox

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
