### ISSUE TITLE
Blocking cdn.segment.com delays epocrates.com/createaccount page load by 30 seconds

### ISSUE THREAD

**Issue by zrhoffman** [disconnectme/disconnect-tracking-protection#380]
### Domain(s) to review (separate domains by comma).

cdn.segment.com

### Rationale for removing, adding, or recategorizing (please provide citations to publicly available information).

Needed in order to create an Epocrates account without waiting for 30 seconds.

### Where domain(s) observed (separate domains by comma).

www.epocrates.com

### Please include example website(s) where the breakage can be observed with clear, repeatable steps to recreate the breakage (separate domains by comma).

1. Open a new Firefox private browsing session
2. Navigate to https://www.epocrates.com/createaccount

Expected result:
Account creation page.

Actual result:
The page takes over 30 seconds to load.

**Comment by disconnectme** [comment]
Thanks for bringing this to our attention. This issue is currently under review.
