### ISSUE TITLE
Consider reclassifying `turn.com` from Content to Advertising

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#46]
Turn (now part of [Amobee](https://www.amobee.com/)) is an [ad tech company](https://www.bloomberg.com/research/stocks/private/snapshot.asp?privcapId=27044065) which has has used very [user-hostile](http://webpolicy.org/2015/01/14/turn-verizon-zombie-cookie/) tracking techniques in the past. They're currently classified as "Content", and thus won't be blocked in Firefox Tracking Protection.

**Comment by carbureted** [comment]
I think that Turn is historically on the content list because of page breakage, but you're right about them being particularly user hostile and it may be time to look at reclassify them.

**Comment by patjack** [comment]
Moved this to Advertising w/commit https://github.com/disconnectme/disconnect-tracking-protection/commit/73723f7da4175df081ac722cbafcb71bb32a4842#diff-f5fb0346ca2de022483b15e81d888f18R6077. Thanks!
