### ISSUE TITLE
nbcnews.com no longer affiliated with Microsoft

### ISSUE THREAD

**Issue by dharb** [disconnectme/disconnect-tracking-protection#47]
nbcnews.com is currently listed under Microsoft: https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L7156

From https://en.wikipedia.org/wiki/NBCNews.com:

"On July 14, 2012, NBC officially announced that Microsoft had sold back its half share of msnbc.com for $300 million"

I'm happy to create a PR for this if you approve of removing it from the list of Microsoft properties.

**Comment by disconnectus** [comment]
This was removed, thanks and sorry for delayed reply.
