### ISSUE TITLE
Not classified suspicious third parties

### ISSUE THREAD

**Issue by yoshimo** [disconnectme/disconnect-tracking-protection#5]
https://webbkoll.dataskydd.net/sv/ uses your database to classify third party requests.
So far the following seem to be missing:
- a.komoona.com
- a248.e.akamai.net
- ad.71i.de
- ad.ad-srv.net
- ad.sxp.smartclip.net
- ad29.ad-srv.net
- ads.stickyadstv.com
- ads.yahoo.com
- adserver.71i.de
- advertiser.wbtrk.net
- aka.spotxcdn.com
- apex.go.sonobi.com
- api-img.billiger.de
- assets-cdn.com
- banners.webmasterplan.com
- bree.com
- c.t4ft.de
- cdn.emetriq.de
- cdn.iqcontentplatform.de
- cdn.komoona.com
- cdn.m-pathy.com
- cdn.onthe.io
- cdn.tradelab.fr
- cdn1.lockerdome.com
- cdn2.lockerdome.com
- cdnjs.cloudflare.com
- cloudfront-labs.amazonaws.com
- cm.adgrx.com
- code.jquery.com
- common.i12.de
- cs.adingo.jp
- cs.gssprt.jp
- cs.komoona.com
- cse.google.com
- d.alcvid.com
- data08.adlooxtracking.com
- data43.adlooxtracking.com
- delivery.swid.switchads.com
- dmp.theadex.com
- dyn.emetriq.de
- event.movad.de
- glaring-torch-8314.firebaseapp.com
- gzhls.at
- hb.vntsm.com
- html-links.com
- images-na.ssl-images-amazon.com
- images.apester.com
- impressions.revenue-tracker.com
- its.tradelab.fr
- j.adlooxtracking.com
- js.himediads.com
- load.s3.amazonaws.com
- lockerdome.com
- match.basebanner.com
- native.sharethrough.com
- p.cpx.to
- p.lp4.io
- partner.vxcp.de
- pde.lp4.io
- pix.impdesk.com
- pixeltrack.eyeviewads.com
- pr-bh.ybp.yahoo.com
- responder.wt-safetag.com
- revenue.com
- s.cpx.to
- s.kau.li
- s.komoona.com
- s.ytimg.com
- s3-eu-central-1.amazonaws.com
- s79.mxcdn.net
- s79.research.de.com
- sc.iasds01.com
- scontent.lrcdn.net
- ssl.p.jwpcdn.com
- stat.komoona.com
- sv.monkeybroker.net
- sync.1rx.io
- sync.go.sonobi.com
- sync.intentiq.com
- sync.rhythmxchange.com
- t.alcvid.com
- t.zqtk.net
- t4ft.de
- track.eyeviewads.com
- tt.onthe.io
- uip.semasio.net
- uobsoe.com
- wss.lockerdome.com
- www.google.com
- www.googletagmanager.com
- x.bidswitch.net

**Comment by holylord03** [comment]
Can you tell me what's all this esp x.bidswitch
