### ISSUE TITLE
`ads-twitter.com` associated with twitter

### ISSUE THREAD

**Issue by birdsarah** [disconnectme/disconnect-tracking-protection#50]
Not sure whether it belongs under advertising or social, but the domain is owned by twitter.

Domain observed on NYTimes, for example.

**Comment by birdsarah** [comment]
https://whois.icann.org/en/lookup?name=ads-twitter.com

**Comment by disconnectus** [comment]
ads-twitter is blocked under the "Disconnect" category that we used for major trackers (Google, FB, Twitter, etc.). We are working on restructuring the list. Thanks for bringing this up, sorry for the delayed reply.
