### ISSUE TITLE
Should adservice.google.ca be on the disconnect list?

### ISSUE THREAD

**Issue by ehsan** [disconnectme/disconnect-tracking-protection#55]
I see the Google tracking `NID` cookie being sent to https://adservice.google.ca/adsid/integrator.js?domain=tpc.googlesyndication.com, see:

![image](https://user-images.githubusercontent.com/168508/44822610-f0b57480-abc9-11e8-91d3-f60d0c455c07.png)

The response headers for this URL includes the following which I found interesting:

`Alt-Svc: quic="googleads.g.doubleclick.net:443"; ma=2592000; v="44,43,39,35",quic=":443"; ma=2592000; v="44,43,39,35"`

**Comment by patjack** [comment]
Thanks, this is now added.
