### ISSUE TITLE
Please whitelist non-personalized/non-tracking AdSense ads

### ISSUE THREAD

**Issue by da2x** [disconnectme/disconnect-tracking-protection#56]
Please consider whitelistsing requests to Google domains that contain the `&npa=1` URL parameter. 

These requests are for non-personalized/non-tracking ads (usually contextual page-relevant ads) that don’t serve ads based on the user’s past browsing behavior, and don’t store information about the page/ad that requested the ad.

> “Although these ads don’t use cookies for ad personalization, they do use cookies to allow for frequency capping, aggregated ad reporting, and to combat fraud and abuse.”

(These are the same exceptions as found in the GDPR.)

More information:
https://support.google.com/adsense/answer/7670312

Disconnect.me should whitelist these to encourage publishers to adopt non-tracking ads.

**Comment by disconnectus** [comment]
Thanks for the note. Definitely want to encourage publishers to adopt privacy friendly advertising. 

We are open to considering this approach, but doesn't Google track user information (IP, webpage, etc.) even when they serve the np ads?

**Comment by da2x** [comment]
@disconnectme, thanks for getting back to me. I forgot to disclose that I’m not affiliated with Google but I am a AdSense publisher.

Google do track IP and webpages and *not associated with a user* for the purposes quoted above (more info at the link.) Notably, they’re the same purposes that are allowed by the GDPR without obtaining permission from the end user so they should be considered priacy friendly under the legal European Union definition. One of the examples that Google gave whe introducing this is that you’ll see page-contextual advertising (ads relevant to the current page) but not ads relevant to your interests or other pages you’ve visited (no stalking/follow ads.)

**Comment by da2x** [comment]
I’m sure Google’s Data Privacy Office wil be happy to provide details.
https://support.google.com/policies/contact/general_privacy_form

**Comment by disconnectus** [comment]
We don't see exact reference to IP and webpage tracking, or a commitment not to associate with users.  Assume you mean this statement: "Although these ads don’t use cookies for ad personalization, they do use cookies to allow for frequency capping, aggregated ad reporting, and to combat fraud and abuse." This doesn't look like a data collection policy, so much as a commitment not to serve ads based on prior data collection. Also, not sure how this would work for users who don't get a consent dialogue i.e. non-EEA users. We will take a closer look. Closing this for now.

**Comment by disconnectus** [comment]
Okay thanks. 

So this looks like "DNT" (Do Not Target) versus a DNT (Do Not Track) policy.
