### ISSUE TITLE
iOS: blocking omtrdc.net (Adobe tracker) breaks investor.hasbro.com

### ISSUE THREAD

**Issue by garvankeeley** [disconnectme/disconnect-tracking-protection#59]
There is a form on this domain that becomes non-interactive when this domain is blocked.
Found on Firefox iOS and Focus iOS:
https://bugzilla.mozilla.org/show_bug.cgi?id=1499201

iOS-specific usage of this list is an ancillary use case of course, so I am filing mostly for future reference; I don't imagine there is a way to change this entry in the list without affecting non-iOS platforms.

**Comment by disconnectus** [comment]
Thanks for the ping, apologies for delay. This has been noted.
