### ISSUE TITLE
Consider reclassifying twimg.com as Content

### ISSUE THREAD

**Issue by Flupsy** [disconnectme/disconnect-tracking-protection#60]
`twimg.com` was moved to Content in 85b100fc9d916a61128b65bbb74ebf39dd26d88a but back to Disconnect in 96254faeeddc83dd31481c700ab7525d41d40fc1.  This breaks profile images when embedding Twitter feeds.  Could it be moved back to Content?

**Comment by disconnectus** [comment]
Twimg.com is a tracker. Right now we're going to keep them blocked, but will continue looking at the issue. Thanks.
