### ISSUE TITLE
cnet.com videos do not play

### ISSUE THREAD

**Issue by dnarcese** [disconnectme/disconnect-tracking-protection#61]
All videos on CNET are being misidentified as trackers and will not play.

**Comment by adamopenweb** [comment]
Example video blocked by basic list in Firefox:
https://www.cnet.com/reviews/apple-macbook-air-2018-review/

**Comment by disconnectus** [comment]
CNET is using an ad-tech company called Instart Logic to tunnel tracking scripts through randomized first-party domains. If these scripts fail to load or unable to callback, videos may not work. This tech not only renders user privacy decisions (tracker protection, private browsing modes, etc) meaningless, but intentionally conceals activity of its tech when a browser's dev console is active, or when network analysis tools like Wireshark or CharlesProxy are in use.
