### ISSUE TITLE
Consider reclassifying shareaholic.com as "Content"

### ISSUE THREAD

**Issue by jmeattle** [disconnectme/disconnect-tracking-protection#62]
All Shareaholic CDN assets (images, fonts, CSS, JS) are loaded from apps.shareaholic.com which causes site functionality and site admin interfaces which are part of WordPress and Drupal Admin areas to break.

For example - WordPress:
http://jay.meattle.com/wp-admin/admin.php?page=shareaholic-settings

Blocking all resources loaded from `shareaholic.com` feels extreme as it breaks functionality across 200,000+ WordPress and Drupal site admin screens.

Possible solution:
Re-classifying shareaholic.com as `Content` seems more appropriate and it would at least stop breaking Admin interfaces in some cases. If someone has the "strict" list turned on in Firefox, then they at least have been given the heads up that site functionality can break.

**Comment by disconnectus** [comment]
What site functionality is broken?

**Comment by disconnectus** [comment]
Shareaholic is properly classified.

**Comment by jmeattle** [comment]
@disconnectus Please give me some time to respond to the follow-up question posted after 2 months. Will post screenshots and details in the next 24-48 hours.

**Comment by disconnectus** [comment]
Okay no problem. Just trying to work our way through open issues.

**Comment by jmeattle** [comment]
I get it :)  Best to open a new issue or post here?  Shareaholic has also always complied with DNT + IP anonymization. Will detail all together.

**Comment by disconnectus** [comment]
Here is fine. We typically deal with whitelist/content requests directly from the company and conduct our review via email.
