### ISSUE TITLE
consider removing the panopticlick test domains

### ISSUE THREAD

**Issue by jawz101** [disconnectme/disconnect-tracking-protection#64]
do-not-tracker.org
eviltracker.net
trackersimulator.org

These try to load code to actually test fingerprinting.  By simply blocking the domains your just saying "Yay, we block those 3 harmless test domains" but the actual tracking techniques that they present would then remain undetected on every other domain on the web.

**Comment by disconnectus** [comment]
These are just test domains that were put on the list as part of collaboration with EFF.
