### ISSUE TITLE
unblock reddit?

### ISSUE THREAD

**Issue by anvaka** [disconnectme/disconnect-tracking-protection#67]
Hello,

Inspired by this discussion: https://news.ycombinator.com/item?id=18890356 - looks like FireFox blocks ajax requests to fetch reddit posts (demo https://jsbin.com/fuyijan/2/edit?js,console)

Is there a way to enable `https://www.reddit.com/r/` and keep everything else as is?

**Comment by disconnectus** [comment]
Thanks for the comment, Reddit third-party social widgets are blocked as trackers.
