### ISSUE TITLE
backtype.com appears to be dead

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#70]
This domain is listed under Twitter, but currently resolves to a GoDaddy parked domain.

**Comment by englehardt** [comment]
I also searched through a recent crawl of the 1M top homepages, and only found one site which still embeds a `backtype.com` resource. The site is `http://www.criminalhistorian.com/` and embeds `http://widgets.backtype.com/tweetcount.js` (which 404s).

**Comment by patjack** [comment]
@englehardt thanks for this info. I just pushed the change that removes it: https://github.com/disconnectme/disconnect-tracking-protection/commit/25e6195ff6e943845beccfc30b5e69f0da61be07
