### ISSUE TITLE
Disqus Ads is not on the blocklist

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#71]
`disqusads.com` is not on the Disconnect list, but does appear to have unique user ID's in cookies sent to its domain. Creating this issue to flag the domain for further review.

An example site that includes this domain: https://www.seekurity.com/blog/general/cryptojacking-by-clickjacking-bypassing-coinhive-opt-in-feature-and-trick-users-into-cryptocurrency-mining/

**Comment by patjack** [comment]
@englehardt thanks for flagging this. We've reviewed at added as tracker https://github.com/disconnectme/disconnect-tracking-protection/commit/daeee5c665f1c9a08bcb265bfee2de3402b1c3cf
