### ISSUE TITLE
s.pubmine.com not on the tracking protection list

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#73]
I noticed that `s.pubmine.com` appears to fire a bunch of tags with UUIDs in them, but is not on Disconnect's list. Flagging it for review.

![Screenshot from 2019-04-12 10-05-06](https://user-images.githubusercontent.com/3280150/56054086-b472f680-5d0a-11e9-862f-c38d5d46ed80.png)

**Comment by englehardt** [comment]
Here's an example site: https://corrinemalcolm.com/

**Comment by englehardt** [comment]
This iframe loads a number of tags that have what appear to be user IDs in their query parameters. It's probably worth looking into them as well. Some examples:
* `https://tracking.emerse.com/match.gif?exchange=bidswitch&ssp=emxdigital&param=...`
* `https://rtb-use.mfadsrvr.com/sync?ssp=bidswitch&seller_network=bidswitch_wordpress&bid_id=....&initiator=me`
* `https://sync.bfmio.com/sync?pid=103&uid=...&dsp_id=&dsp_uuid=`
* `https://cs.admanmedia.com/sync/bsw?bsw_uuid=...&dsp_uuid=&dsp_id=`
* `https://aim.expn.digital/sync_callback?external_user_id=...`
* `https://prg.kargo.com/sync?bidder_id=2&external_user_id=...&dsp_behind_uuid=&dsp_behind_id=&redir_url=`
* `https://sofia.trustx.org/sync?tp_id=1&tp_uid=....&ssp_custom_data=`
* `https://bsw.digitru.st/syncx?dsp_id=250&expires=14&user_id=...`
* `https://public-prod-dspcookiematching.dmxleo.com/dspreply?dspId=25&dspUserId=...`
* `https://sb.freeskreen.com/um?bs=...`
* `https://pr-bh.ybp.yahoo.com/sync/iponweb?bidswitch_ssp_id=lkqd&ssp_user_id=...`
* `https://pixel.s3xified.com/dspsync/?pid=bidswitch&buid=...`
* `https://ads.altitude-arena.com/match?bidder_id=...&external_user_id=...`

Refreshing the page brings in new domains.

**Comment by patjack** [comment]
@englehardt thanks for flagging pubmine and the follow-on requests. We've verified and added pubmine and some of the others that we were able to observe https://github.com/disconnectme/disconnect-tracking-protection/commit/2cc444546c488234be19579eaf7e04563134fafb
