### ISSUE TITLE
pixel.sojern.com is not on the blocklist

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#74]
See https://www.airbnb.com/ for an example:

`https://pixel.sojern.com/idSync/AdX?exchangeProfileId=&sjrn_e=...&sjrn_id=...&sjrn_p=dbm&sjrn_pid=...&sjrn_ula=...&google_error=3`

Flagging for review.

**Comment by patjack** [comment]
@englehardt thanks for flagging this. We just verified and added Sojern.
