### ISSUE TITLE
shareaholic.net needs blocking

### ISSUE THREAD

**Issue by betterwait** [disconnectme/disconnect-tracking-protection#77]
`shareaholic.com` (already blocked) started using `shareaholic.net` to load their main script and tracking:

`https://cdn.shareaholic.net/assets/pub/shareaholic.js`

It was previously:

`https://apps.shareaholic.com/assets/pub/shareaholic.js`

**Comment by patjack** [comment]
@betterwait we added shareaholic.net. Thanks!

**Comment by jmeattle** [comment]
@patjack @betterwait 

This is not classified correctly in my opinion.

**Shareaholic Analytics (analytics.shareaholic.com)**
1. [Shareaholic Analytics](https://www.shareaholic.com/website-tools/content-analytics) works specifically using the following sub-domain:
```
analytics.shareaholic.com
```
2. Incidentally, Shareaholic Analytics [complies with DNT signals](https://www.shareaholic.com/privacy/choices), and has done so for at least 7+ years.
3. Anonymizes user IP address by zeroing the last octet (IPv4) or 80 bits (IPv6) before any logging for EU/EEAA zone. Screenshot from UI:
![image](https://user-images.githubusercontent.com/1015008/58917596-1e998d80-86f5-11e9-8f3e-3fa54ed7cb24.png)

**Shareaholic CDN/Static Assets (shareaholic.net)**
1. `shareaholic.net` is intended to be a cookie-less domain which solely serves to serve static content from a CDN and as such does not fit this blocklist.
2. Blocking this domain causes:
-- sites to not load as content as intended ([including Cookie Consent functionality](https://support.shareaholic.com/hc/en-us/articles/202935963-What-is-the-Cookie-Consent-Banner-) which can cause compliance issues for the site).
-- Blocks Shareaholic's WordPress/Drupal Admin consoles from loading correctly, affecting tens of thousands of site admins on Firefox. Shareaholic is having to resort to notifying admins to [whitelist their domain](https://support.shareaholic.com/hc/en-us/articles/360023147651-Whitelist-Communication-with-Shareaholic-APIs) in Firefox, which is counterproductive to ETP.

In my opinion, the more accurate course of action, keeping with the spirit of ETP would be to:
1. Consider removing completely given Shareaholic Analytics is adhering to the reasoning given by Disconnect in this other [Repo issue](https://github.com/disconnectme/disconnect-tracking-protection/issues/68).
2. As a minimum, reclassify Shareaholic Analytics under **Analytics** (removing it from other categories), and specifically applying it to:
```
analytics.shareaholic.com
```
