### ISSUE TITLE
Lead Forensics tracking domains not blocked

### ISSUE THREAD

**Issue by cylkee** [disconnectme/disconnect-tracking-protection#8]
Intrusive profiling company, [Lead Forensics](http://www.leadforensics.com/), uses the following tracking domains (non-exhaustive list):

```
secure.leadforensics.com
lead-123.com
mon-com-01.com
infra-gtc.com
lansrv040.com
```

Appears to follow the form:

`//www\.example\.com/js/[0-9]+\.js` and noscript as `//www\.example\.com/[0-9]+\.png`

**Comment by JBBrick** [comment]
I would like you to be off my phone I dont know how you got on there

**Comment by JBBrick** [comment]
Why is Lead Forensics on my phone I dont know this company take it off please

**Comment by disconnectus** [comment]
Verified and added. Thanks.
