### ISSUE TITLE
Consider reclassifying 'cxense.com' from Advertising

### ISSUE THREAD

**Issue by bolsen** [disconnectme/disconnect-tracking-protection#80]
Cxense, in the past, was an ad server and the current script still reflects this, but Cxense has not been directly in the adtech business for a while now. However, it remains in the Advertising category. 

Cxense instead offers content personalization services with publisher's own content as well as DMP (this is probably the closest thing to the online ad business, but it is indirect.) Also, there are some cases where publishers would use the service to personalize their own subscription offerings on their own site. While this might be advertising, I would presume this is not the type of advertising that would classify it under the Advertising category here.

I think It is better classified now as "Analytics" and/or "Content".

**Comment by disconnectus** [comment]
Thanks for your submission. Our description of the "Advertising" category does include marketing, which seems to make sense for at least some of Cxense's activities as you describe them. https://disconnect.me/trackerprotection#categories-of-trackers
