### ISSUE TITLE
Consider reclassifying Shareaholic

### ISSUE THREAD

**Issue by jmeattle** [disconnectme/disconnect-tracking-protection#81]
**Shareaholic Analytics (analytics.shareaholic.com)**

1. [Shareaholic Analytics](https://www.shareaholic.com/website-tools/content-analytics) works specifically using the following sub-domain:
     ```
      analytics.shareaholic.com
     ```
2. Incidentally, Shareaholic Analytics [complies with DNT signals](https://www.shareaholic.com/privacy/choices), and has done so for at least 7+ years.
3. Anonymizes user IP address by zeroing the last octet (IPv4) or 80 bits (IPv6) before any logging for EU/EEAA zone. Screenshot from UI:
![image](https://user-images.githubusercontent.com/1015008/58917596-1e998d80-86f5-11e9-8f3e-3fa54ed7cb24.png)

**Shareaholic CDN/Static Assets (shareaholic.net)**
1. `shareaholic.net` is intended to be a cookie-less domain whose purpose is to serve static content from a CDN and as such does not appear to fit the spirit of this blocklist.
2. Blocking this domain (and shareaholic.com site setting API's more generally) causes:
   * Breaks website functionality ([including Cookie Consent functionality](https://support.shareaholic.com/hc/en-us/articles/202935963-What-is-the-Cookie-Consent-Banner-) which can cause unintended compliance issues for the site owner). Since the CDN is currently blocked, zero Shareaholic functionality works on the website.
   * Blocks Shareaholic's WordPress/Drupal Admin consoles from loading correctly, affecting tens of thousands of site admins on Firefox. Settings simply do not load as API calls to edit settings are currently blocked. Shareaholic is having to resort to notifying site admins to [whitelist their domain](https://support.shareaholic.com/hc/en-us/articles/360023147651-Whitelist-Communication-with-Shareaholic-APIs) in Firefox, which is counterproductive to ETP and doesn't feel to be in spirit...

In my opinion, the more accurate course of action would be to:

1. Similar to this [other issue](https://github.com/disconnectme/disconnect-tracking-protection/issues/68#issuecomment-458343248), consider removing Shareaholic completely from the list given Shareaholic Analytics is adhering to DNT, etc. 
2. If Shareaholic Analytics doesn't as yet meet requirements for whitelisting, then:
   * Consider being more specific with the blocklist rule to _Shareaholic Analytics_ under **Analytics** (removing it from other categories), and specifically applying it to:
     ```
     analytics.shareaholic.com
     ```
   * Remove shareaholic.net from the list as it is a static content "cookie-less" domain
   * Remove buzzster.com from the list as it has been defunct for a few years

**Comment by disconnectus** [comment]
Thanks for your submission. Our team is reviewing now.

**Comment by disconnectus** [comment]
After review, we don't find evidence to reverse our classification. It seems Shareaholic is receiving standard HTTP header info (IP and UUID), which we consider PII, on third-party domains. Further, we don't see anything in the Shareaholic policy that suggests you don't retain or share this information. 

If you would like us to take a further look, please cite to specific passages in your privacy policy. Or please add something like the following statement to your privacy policy to make it clear your domain does not meet our definition of tracker: "Shareaholic (and specifically the domains analytics.shareaholic.com) does not collect, store, or share data regarding a particular user’s activity (including IP and unique user identifiers) across multiple websites, or applications that are not owned by Shareaholic."
