### ISSUE TITLE
Consider reclassifying Gleam.io

### ISSUE THREAD

**Issue by thegyppo** [disconnectme/disconnect-tracking-protection#82]
Current classification breaks everything on the js.gleam.io CDN due to Fingerprinting classification. 

This breaks multiple other products that are unrelated impacting thousands of customers.

"We generally unblock tracking sites that require users to transparently and explicitly opt in to collection and retention."

Gleam is a consent based Competition widget (not a tracker), users are not tracked in any way until they explictly fill out the form embedded on a 3rd party page (https://jane.com/giveaway). After which a 3rd party Cookie allows them to remain logged in (so they can come back and complete further entries or check their progress).

No identifiable data is stored or tracked without user consent: https://gleam.io/privacy

Fingerprinting is used as a signal to detect fraudulent Competition entries (from the same user or users creating multiple accounts, which violates our Terms of Service). This is generated but not sent until the user consents by physically entering the Competition on the page.

This also falls within Firefox's policy exceptions:

"Preventing the creation of fraudulent accounts or the completion of fraudulent purchases. For example, a payment processor may examine device properties when processing a payment to determine whether the purchaser is a bot. This allows the payment processor to prevent bots from making purchases with stolen credit cards. Similarly, a captcha provider may use device information to decide whether to prompt users to manually solve a captcha."

**Comment by disconnectus** [comment]
Thanks for your submission. We are actively investigating and will be back to you soon.
