### ISSUE TITLE
Consider reclassifying Ensighten.com

### ISSUE THREAD

**Issue by adurgavich** [disconnectme/disconnect-tracking-protection#84]
1. Ensighten spcifically uses the subdomains nexus.ensighten.com and nexus-test.ensighten.com.
2. Ensighten is a tag management system and does not track users. Instead, it does allow customers to deploy tracking tags; however, these would show up under their own domain name (e.g. google.com, doubleclick.net, etc.).

If you are classifying tag management systems as tracking users, then you should also be blocking Google Tag Manager (www.googletagmanager.com), Adobe DTM/Launch (assets.adobedtm.com), and Tealium (tags.tiqcdn.com, collect.tealiumiq.com).

**Comment by disconnectme** [comment]
Based on review of Ensighten's privacy policy it appears to be properly classified. For example:

"What we collect for customers when they use the Ensighten Services: ...the Ensighten Services will collect certain information about your device. In this context, we collect only the device-related information that our customers instruct us to collect as necessary to provide the Ensighten Services to them. In general, this will typically include certain network-related information, the device’s hardware model, operating system version, and browser type and version. We use this information to help our customers understand the general locale of their visitors, to provide analytics information to our customers about how visitors interact with their digital properties and to monitor, maintain, and improve the Ensighten Services. We encourage our customers to disclose the use of the Ensighten Services in their own privacy statements." https://www.ensighten.com/privacy-policy/
