### ISSUE TITLE
Disconnect may break loading some or all AMP pages

### ISSUE THREAD

**Issue by cramforce** [disconnectme/disconnect-tracking-protection#9]
This was observed with focus ad blocker, but may impact other disconnect based blockers.

See https://github.com/ampproject/amphtml/issues/6163 for our investigation.

To reproduce:

- Activate ad blocker
- Search https://www.google.com for "obama" or "trump"
- Find results marked as "AMP"
- Try to load them
- Loading Spinner is never removed.

In general, AMP does not do any tracking itself (documents and most resources are served from a cookieless domain). It can instrument traditional tracking services, so things should just work if you block those.

**Comment by past** [comment]
@cramforce could you point to a specific page that exhibits this behavior? In my testing I get pages from BBC, CBS, etc. after searching for "trump"  that work fine.

**Comment by cramforce** [comment]
I've heard this happen a lot with reddit pages. "Reddit amp" query yields
one. We were going on widespread Twitter chatter. Will try to repro with
specific steps today.

**Comment by cramforce** [comment]
Ah, apparently it is reddit specific.
See https://gist.github.com/dmccown/2a300939844c87a5c2d787ae2a9a607b

Maybe a regex matching a bit too aggressive?

On Nov 14, 2016 7:00 AM, "Malte Ubl" <malte.ubl@gmail.com> wrote:

I've heard this happen a lot with reddit pages. "Reddit amp" query yields
one. We were going on widespread Twitter chatter. Will try to repro with
specific steps today.

**Comment by choumx** [comment]
Also appears to affect Forbes AMP pages:

> [Info] Content blocker prevented frame displaying https://www.google.com/amp/www.forbes.com/sites/susandudley/2016/11/14/election-could-wake-the-sleeping-cra-giant/?client=safari from loading a resource from https://cdn.ampproject.org/v/www.forbes.com/sites/susandudley/2016/11/14/election-could-wake-the-sleeping-cra-giant/?amp_js_v=6#origin=https%3A%2F%2Fwww.google.com&exp=a4a%3A0&channelid=0&cid=1&dialog=0&prerenderSize=1&visibilityState=prerender&paddingTop=54&history=1&p2r=0&horizontalScrolling=0&csi=0&referrer&storage=1&viewerUrl=https%3A%2F%2Fwww.google.com%2Famp%2Fwww.forbes.com%2Fsites%2Fsusandudley%2F2016%2F11%2F14%2Felection-could-wake-the-sleeping-cra-giant%2F (rs=ACT90oEnPrRtjE0AFhGuu39NRlNGIvTM5A, line 1270)

**Comment by choumx** [comment]
Doesn't repro with the disconnect.me extension on Chrome or Safari with user agent emulation. May be Focus-specific.
