### ISSUE TITLE
Adobe Tag Management

### ISSUE THREAD

**Issue by littlebutty** [disconnectme/disconnect-tracking-protection#91]
Tealium and Google Tag Manager were removed from the list, similarly Adobe Tag Management should also be removed from the list. ([https://github.com/disconnectme/disconnect-tracking-protection/pull/75](https://github.com/disconnectme/disconnect-tracking-protection/pull/75))   

Adobe Dynamic Tag management (DTM) and its new version called Adobe Experience Platform Launch both use the domain **‘adobedtm.com’** and do not have any tracking built in as part of that product offering.  Unlike Google and some of the other Tag Managers that were removed, Adobe does not have tracking built in, nor tracks even aggregate data about the on-client tags firing.  Both DTM and Launch can, and are, used for functional uses cases.   Users can choose to use the Tag Manager to deploy tracking and advertising tools and other tags but even in those cases, the tracking beacons and network calls are NOT made on the **‘adobedtm.com’** domain.  This particular domain is nothing more than a CNAME to a non-Adobe CDN where assets are hosted for download.  This non-Adobe CDN can only provide aggregate data like downloads and hits to the edge; nothing identifiable about the clients making the request to the CDN. Other domains used by products like Adobe Analytics are already covered in other areas of the list.   

Adobe recently updated its public facing Privacy Policy on its Experience Cloud product offerings and included a section about its Tag Management data collection to clarify this position: [https://www.adobe.com/privacy/experience-cloud.html#collect](https://www.adobe.com/privacy/experience-cloud.html#collect)

**Comment by adurgavich** [comment]
++ Ensighten Tag Manager is also being classified and should be removed

https://github.com/disconnectme/disconnect-tracking-protection/issues/84

**Comment by patjack** [comment]
Thanks. This was addressed in this commit: https://github.com/disconnectme/disconnect-tracking-protection/commit/f39cf6021449f3ce1940301aa48ee3c37514de14.
