### ISSUE TITLE
Consider removing ibm.com from IBM's entity

### ISSUE THREAD

**Issue by FrivalszkyP** [disconnectme/disconnect-tracking-protection#92]
I'm a developer at IBM and the product I'm working on is embeddable on third-party sites. 

`ibm.com` was added to the list of services here: https://github.com/disconnectme/disconnect-tracking-protection/commit/94a23927d4e67f12bb7002d03995183983ff65e7#diff-f5fb0346ca2de022483b15e81d888f18

I think this was an oversight on the part of the developer (@carbureted) since tracking and analytics services are not the sole offerings of IBM. Please remove ibm.com from the list, or change it to the specific offending subdomain(s).

Thank you!

**Comment by FrivalszkyP** [comment]
I reworded the title to match the other similar issues. `ibm.com` in itself blocks embeddable services that are using `*.ibm.com` subdomains that have nothing to do with tracking.

**Comment by disconnectme** [comment]
Based on our review, IBM.com is properly classified. However we are open to reviewing additional information and will consider this review ongoing.

**Comment by FrivalszkyP** [comment]
@disconnectme Is this review process open source as well? I'd like to escalate this internally but I'd appreciate more information about what is considered a tracker domain and how your review process works in order to be able to improve the situation.
