### ISSUE TITLE
Add `apps.fbsbx.com` to the blocklist and entitylist.

### ISSUE THREAD

**Issue by englehardt** [disconnectme/disconnect-tracking-protection#95]
The [blocklist](https://github.com/disconnectme/disconnect-tracking-protection/blob/e9f21cba97faff9e914ac16e13f88185116e06e2/services.json#L10984) and the [entitylist](https://github.com/disconnectme/disconnect-tracking-protection/blob/e9f21cba97faff9e914ac16e13f88185116e06e2/entities.json#L4566) both currently include `fbsbx.com`. The public suffix list includes `apps.fbsbx.com`.

In Firefox we ignore the PSL boundary when [checking if a resource should be blocked](https://bugzilla.mozilla.org/show_bug.cgi?id=1203635) , but honor it when we check whether a resource should be whitelisted via the entitylist. This has led to some [website breakage](https://bugzilla.mozilla.org/show_bug.cgi?id=1580416). Consumers which respect the public suffix boundary when parsing a resource (like Firefox will once [Bug 1203635](https://bugzilla.mozilla.org/show_bug.cgi?id=1203635) is fixed) may end up failing to block resources served from `*.apps.fbsbx.com`. Thus, I think it makes sense to add it to the blocklist.

Note that `fbsbx.com` is a valid eTLD+1, so we shouldn't remove it from the list. `apps.fbsbx.com` is an eTLD , so it's a bit like adding `com` to the blocklist for consumers that respect the private suffixes (like Firefox's Tracking Protection). But I think this is fair given that the [stated use of this domain](https://bugzilla.mozilla.org/show_bug.cgi?id=1580416#c0).

**Comment by patjack** [comment]
@englehardt thanks for this info. I looked into this issue and will push an update shortly.
